# -*- coding: utf-8 -*-
"""Conversational AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7IylmPVKLu6EmkPiPCrQMDP8Gx1jMRU

# **Experiment-1**

**Aim:** Write a program to say hi to a chatbot.

**Theory:**

A chatbot is a software application designed to simulate human conversation. In this experiment, we create a simple chatbot named Atiny that interacts with the user by responding to their message with a greeting. This foundational experiment introduces basic input/output (I/O) and string formatting in Python. The program captures the user's name using input(), stores it in a variable, and then uses a formatted string (f-string) to embed the name into the chatbot's greeting. This simulates a basic conversational turn and demonstrates how a bot can use stored data to create a personalized, dynamic response.

**Code:**
"""

def ca1_chatbot():
    chatbot_name = "Atiny"
    username = input("Please tell me your Name")
    user_message = input("Type your message to the chatbot: ")
    response = f"{username}: {user_message} \n {chatbot_name}: Hi there {username} my name is {chatbot_name}, How can I Help You! "
    return response

print(ca1_chatbot())

"""**Result:** The program successfully greeted the user with a personalized message using the chatbot.

# **Experiment-2**

**Aim:** Write a program to convert text to speech.

**Theory:**

This experiment introduces Text-to-Speech (TTS) technology, which is essential for creating voice-enabled agents. It utilizes the gTTS (Google Text-to-Speech) library to perform speech synthesis. The program captures user input as text and passes it to the gTTS function, which synthesizes the corresponding audio stream. This stream is then saved locally as an MP3 audio file. For playback within the Python notebook environment (like Colab), the IPython.display.Audio utility is used to embed and play the generated audio automatically. This process demonstrates the conversion of a static output (text) into a rich, auditory experience, highlighting a crucial component for developing comprehensive voice user interfaces (VUI). The experiment confirms the viability of using cloud services for high-quality speech generation.

**Code:**
"""

# Install required packages
!pip install gTTS

from gtts import gTTS
from IPython.display import Audio
import os

# Get user input
text = input("Enter your text: ")

# Convert text to speech
tts = gTTS(text)

# Save to a file
tts.save("output.mp3")

# Play the audio in Colab
Audio("output.mp3", autoplay=True)

"""**Result:** The program successfully converted the entered text into speech and played the audio output.

# **Experiment-3**

**Aim:** Add various answers to bot for some general questions.

**Theory:**
A chatbot is designed to simulate human conversation by responding to user inputs. This experiment focuses on building a rule-based chatbot named "Echo," primarily demonstrating structured decision-making and key-value storage. The bot maintains a Python dictionary (qa_pairs) where each general query is a key (converted to lowercase for case-insensitivity) and the corresponding factual or conversational response is the value. The core of the bot's logic is a continuous loop that checks if the user's input matches any predefined key. If a match is found, the associated answer is instantly retrieved and displayed. If no direct match occurs, a default response is given. This lookup-based model is the simplest form of Information Retrieval (IR) in a chatbot, proving that interactivity and basic informational utility can be achieved with explicit programming rules and simple data structures.
"""

def ca1_chatbot():
    chatbot_name = "Echo"
    username = input("Please tell me your Name: ")

    print(f"{chatbot_name}: Hi {username}, my name is {chatbot_name}. How can I help you today?")


    qa_pairs = {
        "hi": f"Hello {username}! How are you today?",
        "who created you":"Simmi",
        "how are you": "Thanks for asking. I'm good.",
        "your name": f"My name is {chatbot_name}.",
        "what is computer": "An electronic device that processes data, according to a set of instructions called a program, to perform various tasks.",
        "tell me latest news":"Tesla in Delhi",
        "which country has the highest life expectancy": "Hong Kong",
        "what software company is headquatered in Redmond, Washington": "Microsoft",
        "what is acrophobia a fear of": "It's the fear of heights.",
        "What is sequence of characters that reads the same backward as forward?": "Palindrome",
        "who is my conversionational AI teacher": "Dr Pintu Kumar Ram",
        "bye": f"Goodbye {username}! Have a great day ahead."
    }



    while True:
        user_message = input(f"{username}: ").lower()


        if user_message in ["bye", "exit", "quit","stop"]:
            print(f"{chatbot_name}: Goodbye {username}! Take care.")
            break


        response = qa_pairs.get(user_message, "I am just a kid?")
        print(f"{chatbot_name}: {response}")


# Run the chatbot
ca1_chatbot()

"""**Result:** The program successfully interacted with the user and provided appropriate responses to general questions using predefined answers.

# **Experiment-4**

**Aim:** Text to speech question answers generation.

**Theory:**

This experiment is a functional integration of Experiments 2 and 3, merging the conversational structure with a voice interface. The program uses the gTTS library within a specialized speak() function to audibly deliver every question in the sequence. This ensures the conversational flow is perceived entirely through voice, mimicking a hands-free Voice User Interface (VUI). User responses are captured as text input, but the speak() function is immediately used again to vocally confirm or read back the collected data, reinforcing the interactive experience. This setup effectively demonstrates how to build a bot that manages multi-turn dialogue while utilizing speech synthesis for both output delivery and input acknowledgment, making the bot significantly more engaging than a pure text-based system.

**Code:**
"""

!pip install gTTS

from gtts import gTTS
from IPython.display import Audio, display
import os
import time

# Function to convert text to speech and play it
def speak(text):
    tts = gTTS(text=text, lang='en')
    filename = "temp.mp3"
    tts.save(filename)

    # Play using IPython Audio (works well in notebooks)
    display(Audio(filename, autoplay=True))

    # Wait to let the audio play (adjust if audio is cut short)
    time.sleep(len(text.split()) * 0.4)

    # Optional: delete file if needed
    # os.remove(filename)

# Function to simulate listening (via text input)
def listen():
    response = input("Your answer: ")
    print(f"You said: {response}")
    return response

# Function to ask a question using TTS and get a response
def ask_question(question):
    speak(question)
    answer = listen()
    return answer

# Main program to run the questionnaire
def run():
    questions = [
        "What is your name?",
        "How old are you?",
        "What is your favorite color?",
        "Where are you from?",
        "What is your hobby?"
    ]

    print("Welcome to the Speech-based Questionnaire!\n")
    speak("Welcome to the Speech-based Questionnaire! Let's start.")

    responses = {}

    for question in questions:
        print(f"\nQuestion: {question}")
        answer = ask_question(question)
        responses[question] = answer

    # Final summary
    speak("Thank you for completing the questionnaire! Here are your responses:")

    print("\n--- Summary of Your Responses ---")
    for question, answer in responses.items():
        print(f"{question} → {answer}")
        speak(f"Question: {question}. Answer: {answer}")

# Run the program
if __name__ == "__main__":
    run()

"""**Result:** The program successfully asked questions using speech, recorded user responses, and provided a spoken summary of all answers.

# **Experiment-5**

**Aim:** Integrate other websites and tecnology with bot.

**Theory:**

This experiment upgrades the chatbot to become a powerful utility bot by demonstrating seamless integration with external web services via APIs. It employs the Python requests library to send HTTP GET requests to remote data endpoints (simulated here for OpenWeatherMap and NewsAPI). The bot constructs the request URL dynamically using user-provided parameters (like a city or the command "news"). Upon receiving a response, the bot checks the HTTP status code (ideally 200) and then processes the structured JSON payload to extract and present the required real-time data. This process, known as data fetching, showcases a critical technique for expanding a chatbot's functional scope beyond pre-programmed responses, allowing it to act as an information proxy for the entire web.

**Code:**
"""

pip install requests

import requests

# Function to get weather data
def get_weather(city_name):
    api_key = 'YOUR_API_KEY'  # Get your free API key from https://openweathermap.org/api
    url = f'http://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={api_key}&units=metric'
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        main = data['main']
        weather_desc = data['weather'][0]['description']
        temp = main['temp']
        return f"The current temperature in {city_name} is {temp}°C with {weather_desc}."
    else:
        return "Sorry, I couldn't fetch the weather data."

# Chatbot function to interact with the user
def chatbot():
    print("Hi! I can help you with weather information.")
    while True:
        city = input("Enter the name of the city (or 'quit' to exit): ")
        if city.lower() == 'quit':
            print("Goodbye!")
            break
        else:
            weather_info = get_weather(city)
            print(weather_info)

if __name__ == "__main__":
    chatbot()

import requests

# Function to get latest news
def get_news():
    api_key = 'YOUR_API_KEY'  # Get your free API key from https://newsapi.org/
    url = f'https://newsapi.org/v2/top-headlines?country=us&apiKey={api_key}'
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        articles = data['articles']
        headlines = "\n".join([f"{i+1}. {article['title']}" for i, article in enumerate(articles[:5])])
        return f"Here are the top 5 headlines:\n{headlines}"
    else:
        return "Sorry, I couldn't fetch the news."

# Chatbot function to interact with the user
def chatbot():
    print("Hi! I can tell you the latest news.")
    while True:
        command = input("Type 'news' to get the latest news or 'quit' to exit: ")
        if command.lower() == 'quit':
            print("Goodbye!")
            break
        elif command.lower() == 'news':
            news = get_news()
            print(news)
        else:
            print("Sorry, I didn't understand that command.")

if __name__ == "__main__":
    chatbot()

"""**Result:** The program successfully integrated external web APIs, allowing the chatbot to provide real-time weather updates and news headlines.

# **Experiment-6**

**Aim:** Deploy BOT in your cell phone and test it.

**Theory:**

This experiment focuses on making the bot accessible through fast, modern web deployment. It utilizes the DialoGPT-medium Transformer model for its strong conversational capabilities. The gradio framework is the core tool, as it simplifies the process of creating a public-facing web GUI for the complex AI. To maintain the flow of conversation across multiple turns, the model's intermediate state (the conversation tensor) is stored in a hidden Gradio State component, ensuring responses are contextually relevant. The critical command, demo.launch(share=True), generates a temporary public URL. This share link enables immediate access from any external device, such as a cell phone, allowing for real-world testing of the AI's responsiveness and cross-platform usability without requiring extensive web development expertise.

**Code:**
"""

# Install necessary libraries
!pip install gradio transformers torch -q

# Import libraries
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load the AI model and tokenizer
print("Loading AI model... Please wait.")
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")
print("✅ Model loaded successfully!")

# Define the main function that powers the chatbot
def respond(message, chat_display, chat_history_tensor):
    # 1. Encode the new user message
    new_user_input_ids = tokenizer.encode(message + tokenizer.eos_token, return_tensors='pt')

    # 2. Append the new message to the existing conversation tensor
    bot_input_ids = torch.cat([chat_history_tensor, new_user_input_ids], dim=-1) if chat_history_tensor is not None else new_user_input_ids

    # 3. Generate a response. The output is the new, complete conversation tensor
    new_chat_history_tensor = model.generate(
        bot_input_ids,
        max_length=1250,
        pad_token_id=tokenizer.eos_token_id
    )

    # 4. Decode just the last part of the output tensor to get the bot's response
    bot_response = tokenizer.decode(new_chat_history_tensor[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)

    # 5. Update the chat display history
    updated_chat_display = chat_display + [[message, bot_response]]

    return updated_chat_display, new_chat_history_tensor

# Build the polished Gradio interface
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🤖 AI Chatbot")
    gr.Markdown("A friendly AI Echo. Type your message and press Enter or click Send.")

    # This component stores the conversation tensor, but is not visible
    chat_history_tensor = gr.State()

    # This is the visible chat window
    chatbot_display = gr.Chatbot(label="Conversation", height=500)

    with gr.Row():
      # This is the user's message textbox
      message_textbox = gr.Textbox(
          placeholder="Type your message here...",
          show_label=False,
          scale=4  # Make the textbox take up more space
      )
      # This is the send button
      send_button = gr.Button("Send", variant="primary", scale=1)


    # Define what happens when the user submits their message
    def submit_and_clear(message, chat_display, chat_history_tensor):
        updated_display, updated_tensor = respond(message, chat_display, chat_history_tensor)
        return "", updated_display, updated_tensor

    # Wire up the Send button
    send_button.click(
        submit_and_clear,
        [message_textbox, chatbot_display, chat_history_tensor],
        [message_textbox, chatbot_display, chat_history_tensor]
    )
    # Wire up the Textbox to submit on Enter
    message_textbox.submit(
        submit_and_clear,
        [message_textbox, chatbot_display, chat_history_tensor],
        [message_textbox, chatbot_display, chat_history_tensor]
    )

# Launch the app
demo.launch(share=True, debug=True)

"""**Result:** The program successfully loaded the DialoGPT model and launched a public Gradio web interface for mobile testing.

# **Experiment-7**

**Aim:** Add database to your BOT.

**Theory:**

This experiment is vital for providing the bot with memory and a structured knowledge base. It uses SQLite via the sqlite3 module to create a local, persistent database file. The setup_database function initializes and populates the students table with structured data. The key piece of logic is the query_database function, which takes the user's message, cleans it for processing, and executes a flexible SQL LIKE query against the database. This allows the bot to search for entities (like names or majors). If a query succeeds, the bot returns factual information directly from the database, overriding the general conversational model. This demonstrates the powerful pattern of integrating a knowledge graph or database to handle precise, factual queries reliably.

**Code:**
"""

# Install necessary libraries
!pip install gradio transformers torch -q

# Import libraries
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
import sqlite3
import os
import string # New import for cleaning text

# DATABASE SETUP
def setup_database():
    """Creates and populates our student database."""
    db_file = "student_database.db"
    if os.path.exists(db_file):
        os.remove(db_file) # Start fresh each time

    conn = sqlite3.connect(db_file)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE students (
            id INTEGER PRIMARY KEY, name TEXT NOT NULL, major TEXT NOT NULL,
            enrollment_year INTEGER, interests TEXT
        )''')
    student_data = [
        ('Rahul Kumar', 'Computer Science', 2022, 'is a member of the AI and Robotics club and loves hackathons.'),
        ('Anjali Sharma', 'Economics', 2023, 'is the captain of the university debate team.'),
        ('Vikram Singh', 'Mechanical Engineering', 2022, 'is building a solar-powered car for a national competition.'),
        ('Priya Patel', 'Biology', 2024, 'is researching the effects of urban pollution on local plant life.')
    ]
    cursor.executemany('INSERT INTO students (name, major, enrollment_year, interests) VALUES (?,?,?,?)', student_data)
    conn.commit()
    conn.close()
    print("✅ Student database created and populated successfully!")

# NEW: Upgraded Database Query Logic
def query_database(message):
    """
    Searches the database by breaking the message into keywords.
    """
    conn = sqlite3.connect("student_database.db")
    cursor = conn.cursor()

    # Clean the message: remove punctuation and make it lowercase
    translator = str.maketrans('', '', string.punctuation)
    clean_message = message.lower().translate(translator)

    # Search for each word from the message in the database
    for word in clean_message.split():
        # Skip common and unhelpful words
        if len(word) < 3:
            continue

        cursor.execute("SELECT name, major, enrollment_year, interests FROM students WHERE lower(name) LIKE ? OR lower(major) LIKE ?", ('%' + word + '%', '%' + word + '%'))
        result = cursor.fetchone()

        # If we find a match, stop searching and return it immediately
        if result:
            conn.close()
            return result

    # If no keyword matches, return nothing
    conn.close()
    return None

# AI AND CHATBOT LOGIC
print("Loading AI model... Please wait.")
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")
print("✅ AI Model loaded successfully!")

def respond(message, chat_display, chat_history_tensor):
    db_result = query_database(message)
    if db_result:
        name, major, year, interests = db_result
        grad_year = year + 4
        bot_response = f"I found a student in my database: {name} is studying {major} and is set to graduate in {grad_year}. A fun fact about them: {interests}"
        updated_chat_display = chat_display + [[message, bot_response]]
        return updated_chat_display, chat_history_tensor
    else:
        new_user_input_ids = tokenizer.encode(message + tokenizer.eos_token, return_tensors='pt')
        bot_input_ids = torch.cat([chat_history_tensor, new_user_input_ids], dim=-1) if chat_history_tensor is not None else new_user_input_ids
        new_chat_history_tensor = model.generate(
            bot_input_ids, max_length=1250, pad_token_id=tokenizer.eos_token_id
        )
        bot_response = tokenizer.decode(new_chat_history_tensor[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
        updated_chat_display = chat_display + [[message, bot_response]]
        return updated_chat_display, new_chat_history_tensor

setup_database()

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🤖 AI Chatbot with a Student Database")
    gr.Markdown("Ask me about students like 'Rahul Kumar', 'Anjali', or by majors like 'Economics' or 'Biology'.")
    chat_history_tensor = gr.State()
    chatbot_display = gr.Chatbot(label="Conversation", height=500)
    message_textbox = gr.Textbox(placeholder="Type your message here...")
    def clear_and_respond(message, chat_display, chat_history_tensor):
        updated_display, updated_tensor = respond(message, chat_display, chat_history_tensor)
        return "", updated_display, updated_tensor
    message_textbox.submit(
        clear_and_respond,
        [message_textbox, chatbot_display, chat_history_tensor],
        [message_textbox, chatbot_display, chat_history_tensor]
    )
demo.launch(share=True, debug=True)

"""**Result:** The program successfully created and integrated a SQLite database, allowing the chatbot to retrieve and provide specific student details in response to queries.

# **Experiment-8**

**Aim:** Add the weather data to your BOT and train the BOT weather related questions.

**Theory:**

This experiment develops a basic Natural Language Understanding (NLU) pipeline. The system trains a Logistic Regression classifier using TF-IDF features to correctly identify the user's intent (e.g., weather_current vs. weather_forecast). Once the intent is classified, entity extraction functions search the raw text for key information like city and relative date ("tomorrow"). This combined semantic understanding allows the chatbot's final response function to query a simulated weather database using the extracted parameters. The bot then delivers a highly customized and specific answer, showcasing how machine learning models enable a chatbot to interpret the meaning of a user's complex request rather than just matching keywords.

**Code:**
"""

# =====================================
# STEP 1: Install dependencies
# =====================================
!pip install scikit-learn nltk joblib

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

# =====================================
# STEP 2: Define intents and weather DB
# =====================================
intents = {
  "intents": [
    {
      "tag": "weather_current",
      "examples": [
        "What's the weather in Bangalore today?",
        "How's the weather in Delhi?",
        "Tell me current weather in Mumbai",
        "Is it raining in Kolkata?",
        "Weather in Chennai now"
      ],
      "responses": [
        "Currently in {city}: {summary}"
      ]
    },
    {
      "tag": "weather_forecast",
      "examples": [
        "What's the forecast for Hyderabad tomorrow?",
        "Will it rain in Pune tomorrow?",
        "Weather next week in Jaipur",
        "Forecast for Ahmedabad on Monday"
      ],
      "responses": [
        "Forecast for {city} on {date}: {summary}"
      ]
    },
    {
      "tag": "greeting",
      "examples": ["Hi", "Hello", "Hey", "Good morning"],
      "responses": ["Hello! How can I help you?"]
    },
    {
      "tag": "goodbye",
      "examples": ["Bye", "Goodbye", "See you later"],
      "responses": ["Goodbye! Stay safe."]
    }
  ]
}

# Fake local weather DB
weather_db = {
  "Bangalore": {
    "current": {"temp_c": 29, "condition": "Partly cloudy"},
    "forecast": {
      "2025-10-05": {"high_c": 30, "low_c": 24, "condition": "Sunny"},
      "2025-10-06": {"high_c": 31, "low_c": 25, "condition": "Possible showers"}
    }
  },
  "Mumbai": {
    "current": {"temp_c": 31, "condition": "Humid, light rain"},
    "forecast": {
      "2025-10-05": {"high_c": 33, "low_c": 28, "condition": "Rain"},
      "2025-10-06": {"high_c": 32, "low_c": 27, "condition": "Cloudy"}
    }
  },
  "Delhi": {
    "current": {"temp_c": 35, "condition": "Hot and dry"},
    "forecast": {
      "2025-10-05": {"high_c": 36, "low_c": 26, "condition": "Sunny"},
      "2025-10-06": {"high_c": 34, "low_c": 25, "condition": "Sunny"}
    }
  }
}

# =====================================
# STEP 3: Train simple intent classifier
# =====================================
import re
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

X, y = [], []
for intent in intents["intents"]:
    for ex in intent["examples"]:
        X.append(ex)
        y.append(intent["tag"])

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    tokens = word_tokenize(text)
    return " ".join(tokens)

X_proc = [preprocess(t) for t in X]

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), max_features=2000)),
    ("clf", LogisticRegression(max_iter=1000))
])

X_train, X_test, y_train, y_test = train_test_split(X_proc, y, test_size=0.2, random_state=42)
pipeline.fit(X_train, y_train)

print("Training accuracy:", pipeline.score(X_train, y_train))
print("Test accuracy:", pipeline.score(X_test, y_test))

# =====================================
# STEP 4: Helpers for city + date extraction
# =====================================
import datetime

cities = list(weather_db.keys())
def extract_city(text):
    for c in cities:
        if c.lower() in text.lower():
            return c
    return None

def parse_date_from_text(text):
    today = datetime.date.today()
    if "today" in text.lower():
        return today.isoformat()
    if "tomorrow" in text.lower():
        return (today + datetime.timedelta(days=1)).isoformat()
    return today.isoformat()  # default today

# =====================================
# STEP 5: Chatbot function
# =====================================
import random

def chatbot_response(user_input):
    text_proc = preprocess(user_input)
    intent = pipeline.predict([text_proc])[0]

    if intent == "weather_current":
        city = extract_city(user_input)
        if city and "current" in weather_db[city]:
            cur = weather_db[city]["current"]
            return f"Currently in {city}: {cur['condition']}, {cur['temp_c']}°C"
        return "Please mention a city for weather."

    elif intent == "weather_forecast":
        city = extract_city(user_input)
        date = parse_date_from_text(user_input)
        if city and "forecast" in weather_db[city]:
            forecast = weather_db[city]["forecast"].get(date)
            if forecast:
                return f"Forecast for {city} on {date}: {forecast['condition']}, high {forecast['high_c']}°C low {forecast['low_c']}°C"
            else:
                return f"Sorry, no forecast for {city} on {date}."
        return "Please mention a city for forecast."

    else:
        for it in intents["intents"]:
            if it["tag"] == intent:
                return random.choice(it["responses"])
        return "Sorry, I didn’t understand that."

# =====================================
# STEP 6: Try chatting
# =====================================
print(chatbot_response("What is the weather in Mumbai today?"))
print(chatbot_response("Forecast for Bangalore tomorrow"))
print(chatbot_response("Hi"))
print(chatbot_response("Bye"))

"""**Result:** The program successfully classified user intent and extracted entities to provide accurate current and forecast weather details from a local database.

# **EXPERIMENT-9**

**Aim:** Train the BOT to play music on some websites .

**Theory:**

This experiment demonstrates making the bot actionable by linking conversational commands to an external utility. The bot's logic uses keyword spotting to identify the "play" command and any specific streaming service (e.g., Spotify). It uses the urllib.parse.quote() function to sanitize the extracted song title, which is vital for building a functional URL query string. A stored map links platform names to their base search URLs. When a site is specified, the bot constructs the direct search URL; otherwise, it defaults to YouTube. The final step involves using IPython.display.HTML to render a clickable link in the output, allowing the user to execute the search in their local web browser and fulfill the requested action.

**Code:**
"""

!pip install transformers youtube-search-python

pip install pywhatkit

import webbrowser
import urllib.parse
from IPython.display import HTML, display

# Music websites
music_sites = {
    "spotify": "https://open.spotify.com/search/",
    "gaana": "https://gaana.com/search/",
    "wynk": "https://wynk.in/music/search/",
    "jiosaavn": "https://www.jiosaavn.com/search/"
}

def music_bot():
    print("Music Bot: Hello! Ask me to play a song on YouTube, Spotify, Gaana, Wynk, or JioSaavn.")
    print("Type 'exit' to quit.\n")
    exit
    while True:
        user_input = input("You: ").lower().strip()

        if user_input == "exit":
            print("Bot: Goodbye! Enjoy your music 🎶")
            break

        if "play" in user_input:
            # Extract song name
            song = user_input.replace("play", "").strip()

            if not song:
                print("Bot: Please tell me the song name, e.g., 'Play Pocket Locket on Spotify'")
                continue

            # Check for specific site
            found_site = False
            for site in music_sites:
                if site in user_input:
                    query = urllib.parse.quote(song.replace(site, "").strip())
                    url = music_sites[site] + query
                    print(f"Bot: Searching {song} on {site.title()}... 🎧")
                    webbrowser.open(url)
                    found_site = True
                    break

            # Default to YouTube
            if not found_site:
                query = urllib.parse.quote(song)
                url = f"https://www.youtube.com/results?search_query={query}"
                print(f"Bot: Playing {song} on YouTube... 🎧")
                display(HTML(f'<a href="{url}" target="_blank">Click here to play {song} on YouTube</a>'))

        else:
            print("Bot: Ask me to play a song, e.g., 'Play Don't Copy My Flow on Spotify' or 'Play Pocket Locket'")

if __name__ == "__main__":
    music_bot()

"""**Result:** The program successfully parsed the user's music request and provided a clickable HTML link to perform the corresponding search on the chosen or default music website (YouTube)."""