# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aRpJ4o-ai-JHEDiBLiuvZWiQo9yr2Ty

# **Experiment - 1**

**Aim:** How to Clean Text Manually and with NLTK.

**Theory:**

Text Data Preprocessing is a crucial step in Natural Language Processing (NLP) to prepare raw text for analysis, ensuring that the data is clean, structured, and ready for further tasks like text classification or sentiment analysis. The key steps in our approach are:

**Manual Cleaning**: This involves removing irrelevant elements such as special characters, punctuation, and stopwords, as well as correcting typos. The goal is to reduce noise and ensure that the data is consistent, making it easier for algorithms to process. By cleaning the text manually, we can address specific nuances in the data that automated tools might miss, ensuring a higher quality of preprocessing.

**Manual Tokenization**: In this step, we manually split the text into smaller, meaningful units, typically words or phrases. Manual tokenization allows for more control, such as preserving compound words or specific domain-related terms that automated tokenizers might incorrectly split. This step is crucial in ensuring that tokens are relevant to the specific task or dataset.

**Tokenization using NLTK**: After manual tokenization, we also use NLTK's built-in tokenizers for automated tokenization. NLTK provides efficient methods to handle punctuation, spacing, and other common tokenization issues. This automated step helps in processing large datasets quickly, ensuring consistency and accuracy in tokenization without the need for manual intervention.

**Stemming with NLTK**: Stemming is the process of reducing words to their root form (e.g., "running" becomes "run"). Using NLTK’s stemming algorithms, such as the Porter Stemmer, we eliminate word variants to focus on the base form. This helps in reducing dimensionality and simplifying the dataset, ensuring that the model is not overwhelmed by different word forms and can focus on the core meaning.

These preprocessing steps—manual cleaning, tokenization (both manual and automated with NLTK), and stemming—ensure that the text data is clean, structured, and simplified. This improves the quality of the data, reduces complexity, and leads to better performance in downstream tasks, such as machine learning model training or text analysis.
"""

import string
import re
# load text
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words by white space
words = text.split()
# prepare regex for char filtering
re_punc = re.compile('[%s]' % re.escape(string.punctuation))
# remove punctuation from each word
stripped = [re_punc.sub('', w) for w in words]
print(stripped[:500])

filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words by white space
words = text.split()
# convert to lower case
words = [word.lower() for word in words]
print(words[:100])

!sudo pip install -U nltk

import nltk
nltk.download('all')

from nltk import sent_tokenize
# load data
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into sentences
sentences = sent_tokenize(text)
print(sentences[0])

from nltk.tokenize import word_tokenize
# load data
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words
tokens = word_tokenize(text)
print(tokens[:100])

from nltk.tokenize import word_tokenize
# load data
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words
tokens = word_tokenize(text)
# remove all tokens that are not alphabetic
words = [word for word in tokens if word.isalpha()]
print(words[:100])

from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

import string
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
# load data
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words
tokens = word_tokenize(text)
# convert to lower case
tokens = [w.lower() for w in tokens]
# prepare regex for char filtering
re_punc = re.compile('[%s]' % re.escape(string.punctuation))
# remove punctuation from each word
stripped = [re_punc.sub('', w) for w in tokens]
# remove remaining tokens that are not alphabetic
words = [word for word in stripped if word.isalpha()]
# filter out stop words
stop_words = set(stopwords.words('english'))
words = [w for w in words if not w in stop_words]
print(words[:100])

from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
# load data
filename = '/content/metamorphosis_clean.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words
tokens = word_tokenize(text)
# stemming of words
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in tokens]
print(stemmed[:100])

"""**Result**: Successfully cleaned and preprocessed text using manual techniques and NLTK.

# **Experiment - 2**

**Aim**: To represent text data as numerical features using Bag of Words (BoW) and Term Frequency-Inverse Document Frequency (TF-IDF) methods, enabling text classification and clustering.

**Theory:**

BoW and TF-IDF are techniques for representing text data as numerical vectors, commonly used in machine learning models.

**Bag of Words (BoW)**: Represents text as a "bag" of words, ignoring grammar and order.

Counts the frequency of each word in the document.

**TF-IDF (Term Frequency-Inverse Document Frequency):**
A weighted version of BoW.
Emphasizes rare but significant words while reducing the weight of common words.

Formula:
TF: Frequency of a word in a document


IDF:
log (Total number of documents / Number of documents containing the word)

Applications:
Text classification, clustering, and recommendation systems.
"""

from sklearn.feature_extraction.text import CountVectorizer
# Multiple documents
text = ["It was the best of times", "it was the worst of times", "it was the age of wisdom", "it was the age of foolishness"]
# create the transform
vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(sorted(vectorizer.vocabulary_))

# encode document
vector = vectorizer.transform(text)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

# encode another document
text2 = ["the the the times"]
vector = vectorizer.transform(text2)
print(vector.toarray())

from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ["It was the best of times", "it was the worst of times", "it was the age of wisdom", "it was the age of foolishness"]
# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(text)
# summarize
print(sorted(vectorizer.vocabulary_))
# encode document
vector = vectorizer.transform([text[0]])

print(vectorizer.idf_)

# summarize encoded vector
print(vector.shape)
print(vector.toarray())

"""**Result**: Converted text data into numerical representations using BoW and TF-IDF.

# **Experiment - 3**

**Aim**: To analyze the sentiment (positive or negative) of movie reviews by preprocessing text data, extracting features, and applying a classification model.

**Theory**:

Sentiment analysis involves determining whether a piece of text expresses a positive, negative, or neutral sentiment. It is often used in analyzing reviews, tweets, or other opinion-rich texts.

Steps:

**Preprocessing**: Clean and tokenize text, remove stopwords.

**Feature Extraction**: Convert text into numerical representations (BoW, TF-IDF, or word embeddings).

**Classification**: Use models like Naive Bayes, Logistic Regression, or deep learning for prediction.
"""

import tarfile
import os

# Path to the tar file
filename = '/content/review_polarity.tar'

# Step 1: Extract the files to the specified directory
with tarfile.open(filename, 'r') as tar:
    tar.extractall(path='/content/extracted_files')  # Extracts all files from the tar to this directory

# Step 2: Check the contents of the extracted directory
extracted_files = os.listdir('/content/extracted_files')  # List top-level extracted files/folders
print(extracted_files)  # Shows you the folders like 'txt_sentoken' or other top-level files

# Step 3: Check the structure inside 'txt_sentoken'
extracted_subdirs = os.listdir('/content/extracted_files/txt_sentoken')  # List contents inside 'txt_sentoken' folder
print(extracted_subdirs)  # Should show 'neg' and 'pos' subdirectories

# Load document into memory
def load_doc(filename):
    # open the file as read-only
    file = open(filename, 'r')
    # read all text
    text = file.read()
    # close the file
    file.close()
    return text

from os import listdir

# Load doc into memory
def load_doc(filename):
    # open the file as read-only
    with open(filename, 'r') as file:
        # read all text
        text = file.read()
    return text

# Specify the correct directory path after extraction
directory = '/content/extracted_files/txt_sentoken/neg'

# Walk through all files in the folder
for filename in listdir(directory):
    # Skip files that do not have the right extension
    if not filename.endswith(".txt"):
        continue
    # Create the full path of the file to open
    path = directory + '/' + filename
    # Load document
    doc = load_doc(path)
    print('Loaded %s' % filename)

from os import listdir, path

# Load doc into memory
def load_doc(filename):
    # Open the file as read-only
    with open(filename, 'r') as file:
        # Read all text
        text = file.read()
    return text

# Load all docs in a directory
def process_docs(directory):
    # Check if the directory exists before proceeding
    if not path.exists(directory):
        print(f"Error: The directory {directory} does not exist.")
        return

    # Walk through all files in the folder
    for filename in listdir(directory):
        # Skip files that do not have the right extension
        if not filename.endswith(".txt"):
            continue
        # Create the full path of the file to open
        full_path = path.join(directory, filename)
        # Load document
        doc = load_doc(full_path)
        print(f'Loaded {filename}')

# Check the extracted directory structure
extracted_directory = '/content/extracted_files/txt_sentoken/neg'

# Specify the directory to load (update this path if needed)
directory = extracted_directory  # Change this if your files are in a different location

# Call the function to process the documents
process_docs(directory)

"""Cleaning data"""

# Load doc into memory
def load_doc(filename):
    # Open the file as read-only
    with open(filename, 'r') as file:
        # Read all text
        text = file.read()
    return text

# Update the path if necessary
filename = '/content/extracted_files/txt_sentoken/neg/cv000_29416.txt'  # Adjust this path if needed
text = load_doc(filename)

# Split into tokens by white space
tokens = text.split()

# Print the tokens
print(tokens)

import nltk
nltk.download('stopwords')
import os
import string
import re
from nltk.corpus import stopwords
# Check if the file exists
def load_doc(filename):
    try:
        # Open the file as read-only
        with open(filename, 'r') as file:
            # Read all text
            text = file.read()
        return text
    except FileNotFoundError:
        print(f"Error: The file {filename} does not exist.")
        return None
# Update the path to the correct one
filename = '/content/extracted_files/txt_sentoken/neg/cv000_29416.txt'
# Load the document
text = load_doc(filename)
if text:  # Only proceed if the file was loaded successfully
    # Split into tokens by white space
    tokens = text.split()
    # Prepare regex for character filtering
    re_punc = re.compile('[%s]' % re.escape(string.punctuation))
    # Remove punctuation from each word
    tokens = [re_punc.sub('', w) for w in tokens]
    # Remove remaining tokens that are not alphabetic
    tokens = [word for word in tokens if word.isalpha()]
    # Filter out stop words
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    # Filter out short tokens
    tokens = [word for word in tokens if len(word) > 1]
    # Print the processed tokens
    print(tokens)

# load doc and add to vocab
def add_doc_to_vocab(filename, vocab):
 # load doc
 doc = load_doc(filename)
 # clean doc
 tokens = clean_doc(doc)
 # update counts
 vocab.update(tokens)

# load all docs in a directory
def process_docs(directory, vocab):
 # walk through all files in the folder
 for filename in listdir(directory):
  # skip files that do not have the right extension
  if not filename.endswith(".txt"):
    next
  # create the full path of the file to open
  path = directory + '/' + filename
  # add doc to vocab
  add_doc_to_vocab(path, vocab)

import string
import re
from os import listdir
from collections import Counter
from nltk.corpus import stopwords

# Load document into memory
def load_doc(filename):
    # open the file as read-only
    with open(filename, 'r') as file:
        # read all text
        text = file.read()
    return text

# Turn a doc into clean tokens
def clean_doc(doc):
    # split into tokens by white space
    tokens = doc.split()
    # prepare regex for char filtering
    re_punc = re.compile('[%s]' % re.escape(string.punctuation))
    # remove punctuation from each word
    tokens = [re_punc.sub('', w) for w in tokens]
    # remove remaining tokens that are not alphabetic
    tokens = [word for word in tokens if word.isalpha()]
    # filter out stop words
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    # filter out short tokens
    tokens = [word for word in tokens if len(word) > 1]
    return tokens

# Load doc and add to vocab
def add_doc_to_vocab(filename, vocab):
    # load doc
    doc = load_doc(filename)
    # clean doc
    tokens = clean_doc(doc)
    # update counts
    vocab.update(tokens)

# Load all docs in a directory
def process_docs(directory, vocab):
    # walk through all files in the folder
    for filename in listdir(directory):
        # skip files that do not have the right extension
        if not filename.endswith(".txt"):
            continue
        # create the full path of the file to open
        path = directory + '/' + filename
        # add doc to vocab
        add_doc_to_vocab(path, vocab)

# Define vocab (vocabulary) as a Counter
vocab = Counter()

# Update the directory paths as per the extraction location
neg_directory = '/content/extracted_files/txt_sentoken/neg'
pos_directory = '/content/extracted_files/txt_sentoken/pos'

# Add all docs from the 'neg' and 'pos' directories to vocab
process_docs(neg_directory, vocab)
process_docs(pos_directory, vocab)

# Print the size of the vocab
print(f"Vocabulary size: {len(vocab)}")

# Print the top 50 words in the vocab
print(vocab.most_common(50))

# keep tokens with > 5 occurrence
min_occurane = 5
tokens = [k for k,c in vocab.items() if c >= min_occurane]
print(len(tokens))

def save_list(lines, filename):
 data = '\n'.join(lines)
 file = open(filename, 'w')
 file.write(data)
 file.close()

# save tokens to a vocabulary file
save_list(tokens, 'vocab.txt')

"""Save prepared data"""

def load_doc(filename):
    file = open(filename, 'r')
    text = file.read()
    file.close()
    return text

def clean_doc(doc):
    tokens = doc.split()
    re_punc = re.compile('[%s]' % re.escape(string.punctuation))
    tokens = [re_punc.sub('', w) for w in tokens]
    tokens = [word for word in tokens if word.isalpha()]
    stop_words = set(stopwords.words('english'))
    tokens = [w for w in tokens if not w in stop_words]
    tokens = [word for word in tokens if len(word) > 1]
    return tokens

def save_list(lines, filename):
    data = '\n'.join(lines)
    file = open(filename,'w')
    file.write(data)
    file.close()

# load doc, clean and return line of tokens
def doc_to_line(filename, vocab):
    doc = load_doc(filename)
    tokens = clean_doc(doc)
# filter by vocab
    tokens = [w for w in tokens if w in vocab]
    return ''.join(tokens)

def process_docs(directory, vocab):
    lines = list()
    for filename in listdir(directory):
        if not filename.endswith(".txt"):
            next
        path = directory + '/' + filename
# load and clean the doc
        line = doc_to_line(path, vocab)
# add to list
        lines.append(line)
    return lines

import tarfile
from os import listdir
from os.path import join

# Extract the tar file
archive_path = '/content/review_polarity.tar'
extracted_dir = '/content/review_polarity'

# Extract if not already extracted
if not os.path.exists(extracted_dir):
    with tarfile.open(archive_path, 'r') as tar:
        tar.extractall(path=extracted_dir)

# Load vocabulary
vocab_filename = 'vocab.txt'
vocab = load_doc(vocab_filename)
vocab = vocab.split()
vocab = set(vocab)

# Prepare negative reviews
negative_lines = process_docs(join(extracted_dir, 'txt_sentoken/neg'), vocab)
save_list(negative_lines, 'negative.txt')

# Prepare positive reviews
positive_lines = process_docs(join(extracted_dir, 'txt_sentoken/pos'), vocab)
save_list(positive_lines, 'positive.txt')

with open('negative.txt', 'r') as file:
    negative_lines = file.readlines()
with open('positive.txt', 'r') as file:
    positive_lines = file.readlines()

print("Negative lines:", negative_lines[:5])
print("Positive lines:", positive_lines[:5])

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

# Combine positive and negative lines
all_reviews = negative_lines + positive_lines
all_labels = [0] * len(negative_lines) + [1] * len(positive_lines)  # 0 for negative, 1 for positive

# Split the data
X_train, X_test, y_train, y_test = train_test_split(all_reviews, all_labels, test_size=0.2, random_state=42)

# Convert text data into numerical data using TF-IDF
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train a Naive Bayes classifier
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred = model.predict(X_test_tfidf)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Example of predicting sentiment for new reviews
new_reviews = ["The movie was fantastic! I loved it.", "I hated the film. It was boring and slow."]
new_reviews_tfidf = vectorizer.transform(new_reviews)
predictions = model.predict(new_reviews_tfidf)
print(predictions)  # Output: 1 for positive, 0 for negative

!tar -xvf /content/review_polarity.tar

"""**Result**: Successfully classified movie reviews into positive and negative sentiments.

# **Experiment - 4**

**Aim**: To implement Word2Vec models (CBOW and Skip-gram) for generating word embeddings that capture semantic and syntactic relationships between words.

**Theory**:

CBOW (Continuous Bag of Words) and Skip-gram are two models used in Word2Vec, a neural network-based technique for learning word embeddings.

**CBOW (Continuous Bag of Words)**:

Predicts a target word based on the context (surrounding words).

Input: Context words.

Output: Target word.

Example: For the sentence "I love natural language processing," CBOW uses "I," "love," "language," "processing" to predict "natural."

**Skip-gram**:

Predicts context words based on a given target word.

Input: Target word.

Output: Context words.

Example: For the sentence "I love natural language processing," Skip-gram uses "natural" to predict "I," "love," "language," "processing."

**Applications**:
Semantic similarity.
Machine translation.
Question answering systems.
"""

import re
import numpy as np
from collections import Counter

# Sample corpus (you can use your own corpus)
corpus = [
    "I love machine learning",
    "Deep learning is great",
    "Natural language processing is awesome"
]

# Tokenize text (simple tokenization)
def preprocess_text(corpus):
    corpus = [re.sub(r'\W+', ' ', text.lower()) for text in corpus]  # Remove non-word characters and lowercase
    corpus = [text.split() for text in corpus]  # Tokenize by spaces
    return corpus

tokens = preprocess_text(corpus)

# Generate context-target pairs (for CBOW and Skip-gram)
def generate_context_target_pairs(corpus, window_size=1):
    context_target_pairs = []
    for sentence in corpus:
        for idx, word in enumerate(sentence):
            # CBOW: context is surrounding words, target is the current word
            # Skip-gram: context is surrounding words, target is the current word
            start = max(0, idx - window_size)
            end = min(len(sentence), idx + window_size + 1)

            context = [sentence[i] for i in range(start, end) if i != idx]
            target = word
            context_target_pairs.append((context, target))
    return context_target_pairs

context_target_pairs = generate_context_target_pairs(tokens)

import re
import numpy as np
from collections import Counter
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer

# Sample corpus (you can use your own corpus)
corpus = [
    "I love machine learning",
    "Deep learning is great",
    "Natural language processing is awesome"
]

# Tokenize text (simple tokenization)
def preprocess_text(corpus):
    corpus = [re.sub(r'\W+', ' ', text.lower()) for text in corpus]  # Remove non-word characters and lowercase
    corpus = [text.split() for text in corpus]  # Tokenize by spaces
    return corpus

tokens = preprocess_text(corpus)

# Generate context-target pairs (for CBOW and Skip-gram)
def generate_context_target_pairs(corpus, window_size=1):
    context_target_pairs = []
    for sentence in corpus:
        for idx, word in enumerate(sentence):
            # CBOW: context is surrounding words, target is the current word
            # Skip-gram: context is surrounding words, target is the current word
            start = max(0, idx - window_size)
            end = min(len(sentence), idx + window_size + 1)

            context = [sentence[i] for i in range(start, end) if i != idx]
            target = word
            context_target_pairs.append((context, target))
    return context_target_pairs

context_target_pairs = generate_context_target_pairs(tokens)

# Flatten corpus into a list of words
flat_corpus = [word for sentence in tokens for word in sentence]

# Create a tokenizer to map words to integers
tokenizer = Tokenizer()
tokenizer.fit_on_texts(flat_corpus)

vocab_size = len(tokenizer.word_index) + 1  # Including 0 for padding
word_to_index = tokenizer.word_index
index_to_word = {index: word for word, index in word_to_index.items()}

# Create training data (pad the contexts)
def create_training_data(context_target_pairs, max_len):
    contexts, targets = [], []
    for context, target in context_target_pairs:
        context_indices = [word_to_index[word] for word in context]
        target_index = word_to_index[target]
        contexts.append(context_indices)
        targets.append(target_index)

    # Pad sequences to ensure all contexts are of the same length
    contexts_padded = pad_sequences(contexts, maxlen=max_len, padding='post', truncating='post')

    return np.array(contexts_padded), np.array(targets)

# Calculate the maximum context length
max_len = max(len(context) for context, _ in context_target_pairs)

contexts, targets = create_training_data(context_target_pairs, max_len)

# Define Skip-gram Model
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=50, input_length=contexts.shape[1]),  # Embedding layer
    Flatten(),  # Flatten the embedding output
    Dense(50, activation='relu'),  # Hidden layer
    Dense(vocab_size, activation='softmax')  # Output layer with softmax
])

model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(contexts, targets, epochs=10, batch_size=2)

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Extract word embeddings from the trained Skip-gram model
embeddings = model.layers[0].get_weights()[0]  # Get the weights from the embedding layer

# Reduce the dimensionality of the embeddings using PCA (to 2D)
pca = PCA(n_components=2)
reduced_embeddings = pca.fit_transform(embeddings)

# Plot the 2D word embeddings
plt.figure(figsize=(10, 10))
for word, idx in word_to_index.items():
    x, y = reduced_embeddings[idx]
    plt.scatter(x, y)
    plt.text(x + 0.1, y + 0.1, word, fontsize=12)

plt.title('2D PCA of Word Embeddings')
plt.grid(True)
plt.show()

"""**Result**: Generated word embeddings capturing semantic and syntactic relationships between words.

# **Experiment - 5**

**Aim**: To fine-tune the BERT (Bidirectional Encoder Representations from Transformers) model for classifying movie reviews as positive or negative.

**Theory**:
BERT (Bidirectional Encoder Representations from Transformers) is a transformer-based model developed by Google for Natural Language Processing (NLP) tasks. BERT captures bidirectional context, making it effective for understanding the nuances of language.

Fine-tuning involves training a pre-trained model (BERT in this case) on a specific task, such as sentiment analysis, using labeled data. The process includes:

**Tokenization**: Converting text into numerical input using a tokenizer compatible with BERT.

**Dataset Preparation**: Splitting data into training and evaluation sets.

**Training**: Adjusting the weights of the BERT model to improve its performance on the specific task.

**Evaluation**: Measuring model accuracy and performance using evaluation data.

**Inference**: Using the fine-tuned model to classify new text inputs.

Sentiment analysis involves classifying text (e.g., movie reviews) into categories like positive or negative sentiments. This experiment uses a labeled dataset of movie reviews with their corresponding sentiment labels for fine-tuning BERT.

**Codes:**
"""

!pip install transformers datasets torch

from transformers import BertTokenizer, BertForSequenceClassification
from transformers import Trainer, TrainingArguments
from datasets import load_dataset, Dataset
import torch

# Load and Preprocess Dataset
def preprocess_data(reviews, labels):
    data = {
        "text": reviews,
        "label": labels
    }
    return Dataset.from_dict(data)

# Example Data (Replace with your movie reviews dataset)
reviews = ["The movie was fantastic!", "I did not enjoy the movie.", "Absolutely amazing film!", "The movie was boring."]
labels = [1, 0, 1, 0] # 1: Positive, 0: Negative

dataset = preprocess_data(reviews, labels)

# Tokenization
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Load Pretrained BERT Model
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

# Prepare for Training
tokenized_dataset = tokenized_dataset.rename_columns({"label": "labels"})
tokenized_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

# Split dataset for training and evaluation
train_size = int(0.8 * len(tokenized_dataset))
train_dataset = tokenized_dataset.select(range(train_size))
eval_dataset = tokenized_dataset.select(range(train_size, len(tokenized_dataset)))

# Training Configuration
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    save_steps=10
)

# Trainer for Fine-Tuning BERT
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer
)

# Train the Model
trainer.train()

# Evaluate the Model
trainer.evaluate()

# Make Predictions (Inference)
def predict_sentiment(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)
    outputs = model(**inputs)
    prediction = torch.argmax(outputs.logits, dim=-1).item()
    return "Positive" if prediction == 0 else "Negative"

# Example Inference
sample_text = "The movie was a masterpiece!"
print(f"Review: '{sample_text}' -> Sentiment: {predict_sentiment(sample_text)}")

"""**Result**:The BERT model was successfully fine-tuned to classify movie reviews with high accuracy into positive or negative sentiments.

# **Experiment - 6**

**Aim**: Implement Word2Vec using numpy and classify based on SVM and Naive Bayes.

**Theory**:

**1. Word2Vec:**
Word2Vec is a technique that transforms words into continuous vector representations, capturing semantic relationships. It uses two models:

**CBOW (Continuous Bag of Words)**: Predicts a word based on its context.

**Skip-gram**: Predicts the surrounding context from a given word.
In this experiment, we use the Skip-gram model to generate word embeddings from the text dataset.

**2. Support Vector Machine (SVM)**:
SVM is a supervised learning algorithm used for classification tasks. It separates data points with a hyperplane to maximize the margin between different classes.

**3. Naive Bayes**:
Naive Bayes is a probabilistic classifier based on Bayes' theorem. It assumes independence between features and works well with text classification problems.

**4. Principal Component Analysis (PCA)**:
PCA reduces the dimensionality of feature vectors while retaining most of the variance, making the data suitable for classification algorithms like SVM and Naive Bayes.

**Workflow**:

1. **Data Preprocessing**: Cleaning text and converting categories to numerical labels.
2. **Tokenization**: Breaking sentences into individual words.
3. **Word Embedding**: Training Word2Vec to convert words into vectors.
4. **Dimensionality Reduction**: Using PCA to reduce vector dimensions.
5. **Classification**:

  **SVM**: For high-dimensional classification.

  **Naive Bayes**: Using sentence embeddings for probabilistic classification.
6. **Evaluation**: Comparing model accuracy on the test dataset.
"""

import numpy as np
import pandas as pd
import gensim
import nltk
import re
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
data = pd.read_csv('/content/SPAM text message 20170820 - Data.csv')
data.head()
# We'll write a function which will clean the text and prepare it.
def cleanText(text):
    cleaned = re.sub("[^a-zA-Z0-9']"," ", text)
    lowered = cleaned.lower()
    return lowered.strip()
# Testing the function
cleanText("Let's test our function, by writing this string!")
x, y = np.asarray(data["Message"]), np.asarray(data["Category"])
x_cleaned = [cleanText(t) for t in x]
x_cleaned[:4]
# Also we should convert our categories to the integer labels
label_map = {cat: index for index, cat in enumerate(np.unique(y))}
y_prep = np.asarray([label_map[l] for l in y])

x_tokenized = [[w for w in sentence.split(" ") if w != ""] for sentence in x_cleaned]
x_tokenized[0]

import time
start = time.time()
# Assuming x_tokenized is a list of tokenized messages
model = gensim.models.Word2Vec(
    x_tokenized,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)
end = round(time.time() - start, 2)
print("This process took", end, "seconds.")

model.wv.most_similar("free")

class Sequencer():
    def __init__(self, all_words, max_words, seq_len, embedding_matrix):
        self.seq_len = seq_len
        self.embed_matrix = embedding_matrix
        temp_vocab = list(set(all_words))
        self.vocab = []
        self.word_cnts = {}
        for word in temp_vocab:
            count = len([0 for w in all_words if w == word])
            self.word_cnts[word] = count
        counts = list(self.word_cnts.values())
        indexes = list(range(len(counts)))
        cnt = 0
        while cnt + 1 != len(counts):
            cnt = 0
            for i in range(len(counts) - 1):
                if counts[i] < counts[i + 1]:
                    counts[i + 1], counts[i] = counts[i], counts[i + 1]
                    indexes[i], indexes[i + 1] = indexes[i + 1], indexes[i]
                else:
                    cnt += 1
        for ind in indexes[:max_words]:
            self.vocab.append(temp_vocab[ind])
    def textToVector(self, text):
        tokens = text.split()
        len_v = len(tokens) - 1 if len(tokens) < self.seq_len else self.seq_len - 1
        vec = []
        for tok in tokens[:len_v]:
            try:
                vec.append(self.embed_matrix[tok])
            except Exception as E:
                pass
        last_pieces = self.seq_len - len(vec)
        for i in range(last_pieces):
            vec.append(np.zeros(100,))
        return np.asarray(vec).flatten()
sequencer = Sequencer(
    all_words=[token for seq in x_tokenized for token in seq],
    max_words=1200,
    seq_len=15,
    embedding_matrix=model.wv
)
test_vec = sequencer.textToVector("i am in love with you")
test_vec

test_vec.shape

# But before creating a PCA model using scikit-learn let's create
# vectors for our each vector
x_vecs = np.asarray([sequencer.textToVector(" ".join(seq)) for seq in x_tokenized])
print(x_vecs.shape)

from sklearn.decomposition import PCA
pca_model = PCA(n_components=50)
pca_model.fit(x_vecs)
print("Sum of variance ratios: ",sum(pca_model.explained_variance_ratio_))

x_comps = pca_model.transform(x_vecs)
x_comps.shape

x_train,x_test,y_train,y_test = train_test_split(x_comps,y_prep,test_size=0.2,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

start = time.time()
svm_classifier = SVC()
svm_classifier.fit(x_train,y_train)
start = time.time()
svm_classifier = SVC()
svm_classifier.fit(x_train,y_train)
end = time.time()
process = round(end-start,2)
print("Support Vector Machine Classifier has fitted, this process took {} seconds".format(process))

svm_classifier.score(x_test,y_test)

import numpy as np
from collections import defaultdict
import random
# Preprocess text and generate vocabulary
def preprocess(text):
    text = text.lower().split()
    vocab = set(text)
    word2idx = {word: idx for idx, word in enumerate(vocab)}
    idx2word = {idx: word for word, idx in word2idx.items()}
    return text, word2idx, idx2word
# Generate training data for Word2Vec (skip-gram)
def generate_training_data(text, word2idx, window_size=2):
    data = []
    for i, word in enumerate(text):
        target_word_idx = word2idx[word]
        context_indices = list(range(max(0, i - window_size), i)) + list(range(i + 1, min(len(text), i + window_size + 1)))
        for context_idx in context_indices:
            context_word_idx = word2idx[text[context_idx]]
            data.append((target_word_idx, context_word_idx))
    return np.array(data)
# Initialize the model
def initialize_model(vocab_size, embedding_size):
    W1 = np.random.randn(vocab_size, embedding_size)
    W2 = np.random.randn(embedding_size, vocab_size)
    return W1, W2
# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum(axis=0)
# Train the Word2Vec model
def train_word2vec(text, vocab_size, word2idx, embedding_size=10, learning_rate=0.001, epochs=5000):
    W1, W2 = initialize_model(vocab_size, embedding_size)
    data = generate_training_data(text, word2idx)
    for epoch in range(epochs):
        loss = 0
        for target_idx, context_idx in data:
            h = W1[target_idx]
            u = np.dot(W2.T, h)
            y_pred = softmax(u)
            y_true = np.zeros(vocab_size)
            y_true[context_idx] = 1
            error = y_pred - y_true
            W2 -= learning_rate * np.outer(h, error)
            W1[target_idx] -= learning_rate * np.dot(W2, error)
            loss += -np.log(y_pred[context_idx])
        # Log loss every 100 epochs
        if epoch % 100 == 0:
            print(f"Epoch {epoch}, Loss: {loss}")
    return W1, W2
# Get word embeddings from trained model
def get_word_embeddings(W1, idx2word):
    word_embeddings = {}
    for idx, word in idx2word.items():
        word_embeddings[word] = W1[idx]
    return word_embeddings
# Example usage:
text = "the quick brown fox jumps over the lazy dog"
text, word2idx, idx2word = preprocess(text)
vocab_size = len(word2idx)
# Train the Word2Vec model with smaller learning rate and more epochs
W1, W2 = train_word2vec(text, vocab_size, word2idx, learning_rate=0.001, epochs=5000)
# Get word embeddings
word_embeddings = get_word_embeddings(W1, idx2word)
# Display word embeddings
print("Word Embeddings:")
for word, embedding in word_embeddings.items():
    print(f"{word}: {embedding}")

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
# Function to get sentence embeddings by averaging word embeddings
def get_sentence_embeddings(texts, word_embeddings):
    sentence_embeddings = []
    for text in texts:
        words = text.split()
        embeddings = [word_embeddings[word] for word in words if word in word_embeddings]
        if embeddings:  # Ensure there are embeddings before averaging
            sentence_embedding = np.mean(embeddings, axis=0)
        else:
            sentence_embedding = np.zeros(len(next(iter(word_embeddings.values()))))  # Zero vector if no words match
        sentence_embeddings.append(sentence_embedding)
    return np.array(sentence_embeddings)
# Example sentences and labels
sentences = [
    "the quick brown fox",
    "jumps over the lazy dog",
    "the dog is lazy",
    "quick fox jumps"
]
labels = ["animal_action", "animal_action", "description", "animal_action"]
# Preprocess sentences and get sentence embeddings
sentence_embeddings = get_sentence_embeddings(sentences, word_embeddings)
# Encode labels
label_encoder = LabelEncoder()
labels_encoded = label_encoder.fit_transform(labels)
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(sentence_embeddings, labels_encoded, test_size=0.2, random_state=42)
# Train Gaussian Naive Bayes classifier
gnb_classifier = GaussianNB()
gnb_classifier.fit(X_train, y_train)
# Test classifier
y_pred = gnb_classifier.predict(X_test)
# Evaluate classifier
accuracy = np.mean(y_pred == y_test)
print(f"Accuracy: {accuracy * 100:.2f}%")

"""# **Experiment - 7**

**Aim :** Visualize data with t-distributed stochastic neighbor embedding (t-SNE).

**Theory**:

The **Bigram model** predicts the next word based on the previous word. In this experiment, a **Neural Network (NN)** is used to learn these predictions from text data.

1. **Embedding Layer**: Converts words into dense vectors (word embeddings).
2. **Dense Layer**: Processes the embeddings to learn relationships between words.
3. **Output Layer**: Predicts the next word using softmax activation, outputting word probabilities.
**Steps**:
1. **Tokenization**: Split text into words and assign unique integer IDs.
2. **Bigrams**: Extract pairs of consecutive words as input-output pairs.
3. **One-hot Encoding**: Convert output words into binary vectors.
"""

import numpy as np
from sklearn.manifold import TSNE
from sklearn.datasets import fetch_openml
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd
from sklearn.decomposition import PCA

# Load MNIST dataset
mnist = fetch_openml('mnist_784', version=1)
X = mnist.data / 255.0
y = mnist.target

# Show unique categories (digits) in the dataset
unique_digits = np.unique(y)
print("Unique categories (digits) in the dataset:", unique_digits)

# Select 10000 random points
np.random.seed(42) # For reproducibility
indices = np.random.choice(range(X.shape[0]), size=10000, replace=False)
X_subset = X.iloc[indices]
y_subset = y.iloc[indices]

# Apply PCA for initial dimensionality reduction
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_subset)
# Plotting with Matplotlib
plt.figure(figsize=(12, 8))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y_subset.astype(int), cmap='tab10', s=1)
plt.colorbar(scatter)
plt.title('PCA of MNIST')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.show()

# Apply t-SNE
tsne = TSNE(n_components=2, perplexity=30, n_iter=1000, random_state=42)
X_tsne = tsne.fit_transform(X_subset)

# Plot the result
plt.figure(figsize=(12, 8))
scatter = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y_subset.astype(int), cmap='tab10', s=1)
plt.legend(*scatter.legend_elements(), title="Digits")
plt.title('t-SNE of MNIST')
plt.show()

# Create a DataFrame for t-SNE results
tsne_df = pd.DataFrame(X_tsne, columns=['t-SNE 1', 't-SNE 2'])
tsne_df['Digit'] = y_subset.astype(int)

# Plot using Plotly
fig = px.scatter(tsne_df, x='t-SNE 1', y='t-SNE 2', color='Digit',
                 title='t-SNE of MNIST', labels={'Digit': 'Digit Class'})
fig.show()

"""# **Experiment - 8**

**Aim**: To implement Bigram using Neural Network.

**Theory**:

The **Bigram model** predicts the next word based on the previous word. In this experiment, a **Neural Network (NN)** is used to learn these predictions from text data.

1. **Embedding Layer**: Converts words into dense vectors (word embeddings).
2. **Dense Layer**: Processes the embeddings to learn relationships between words.
3. **Output Layer**: Predicts the next word using softmax activation, outputting word probabilities.
**Steps**:
1. **Tokenization**: Split text into words and assign unique integer IDs.
2. **Bigrams**: Extract pairs of consecutive words as input-output pairs.
3. **One-hot Encoding**: Convert output words into binary vectors.
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample text corpus (you can replace this with any corpus you want)
corpus = [
    "I love machine learning",
    "Machine learning is fun",
    "I enjoy learning new things",
    "Learning is important",
    "Machine learning models are powerful"
]

# Tokenize the corpus
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1  # +1 for padding token
# Convert text into sequences of tokens
sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[i-1:i+1]  # Bigram: the previous word and the current one
        sequences.append(sequence)

# Convert sequences into numpy array
sequences = np.array(sequences)
# Prepare the input and output (X, y)
X = sequences[:, 0]  # First word in the bigram (input)
y = sequences[:, 1]  # Second word in the bigram (output)
# Reshape X to fit the neural network
X = X.reshape((X.shape[0], 1))
# One-hot encode the output labels (y)
y = tf.keras.utils.to_categorical(y, num_classes=total_words)
print("Total words:", total_words)

# Check the shapes
print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

# define the model
model = Sequential()
# Add an embedding layer: this learns a dense vector representation for each word
model.add(Embedding(input_dim=total_words, output_dim=10, input_length=1))  # Embedding layer
# Add a dense layer with ReLU activation
model.add(Dense(50, activation='relu'))
# Flatten the output from the dense layer before passing it to the final layer
model.add(Flatten())
# Output layer with softmax activation for word prediction
model.add(Dense(total_words, activation='softmax'))
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Explicitly build the model to ensure layers are initialized
model.build(input_shape=(None, 1))  # This forces the model to build with a specific input shape
# Print model summary
model.summary()

# Train the model
model.fit(X, y, epochs=10, verbose=0)

from tensorflow.keras.preprocessing.sequence import pad_sequences

def predict_next_word(model, tokenizer, text, top_n=3, max_sequence_length=50):
    # Convert the text input into tokens
    sequence = tokenizer.texts_to_sequences([text])[0]

    # Pad the sequence to match the expected input length
    sequence = pad_sequences([sequence], maxlen=1, padding='pre')  # Since model expects length 1 input

    # Predict the next word
    predicted_probs = model.predict(sequence, verbose=0)

    # Get the indices of the top N predicted words
    predicted_indices = predicted_probs[0].argsort()[-top_n:][::-1]

    # Convert indices back to words
    predicted_words = [tokenizer.index_word[index] for index in predicted_indices]
    return predicted_words

input_text = "machine learning"
predicted_words = predict_next_word(model, tokenizer, input_text)
print(f"Given the input '{input_text}', the top predicted next words are: {predicted_words}")

"""# **Experiment - 9**

**Aim**:To implement Matrix Factorization (SVD).

**Theory**:

Matrix Factorization using Singular Value Decomposition (SVD) is a key technique in recommendation systems to predict missing entries in a user-item interaction matrix, such as user ratings of products or movies.

SVD decomposes the matrix R into three matrices:

  **U (User matrix)**: Represents the relationship between users and latent features (hidden preferences).

  **Sigma (Singular values)**: Contains the strength of each latent factor, reflecting the importance of each feature.

  **Vt (Item matrix)**: Represents the relationship between items and latent features.
  
The decomposition is expressed as
R≈U⋅Σ⋅V^T
 . By retaining only the top singular values, SVD reduces the matrix’s dimensionality, capturing the most important patterns in user-item interactions. This allows the system to predict missing ratings, improving recommendations. By revealing hidden relationships, SVD helps systems suggest relevant items, enhancing user experience with accurate, personalized predictions based on past behaviors.
"""

import numpy as np
from scipy.sparse.linalg import svds

# Step 1: Example matrix (user-item ratings matrix)
R = np.array([[5, 4, 0, 1, 0],
              [4, 0, 0, 1, 1],
              [1, 1, 0, 5, 4],
              [0, 1, 5, 4, 0],
              [1, 0, 5, 4, 5]])

# Convert to float
R = R.astype(float)

# Step 2: Apply SVD
# We will get the U, Sigma, and Vt matrices
U, sigma, Vt = svds(R, k=2)  # 'k' is the number of latent factors you want

# Step 3: Reconstruct the matrix
sigma = np.diag(sigma)  # Convert sigma to diagonal form
R_pred = np.dot(np.dot(U, sigma), Vt)  # Reconstruct the matrix

# Step 4: Show the predicted matrix
print("Original Matrix:")
print(R)
print("\nReconstructed Matrix:")
print(R_pred)

"""**Result**: Sucessfully implemented Matrix Factorization (SVD).

# **Experiment - 10**

**Aim**: To perform text classification using a) LSTM b)RNN

a) LSTM
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

# Example Data (X: Text, y: Labels)
texts = [
    "I love programming",
    "Python is great for data science",
    "I hate bugs in the code",
    "Data science is amazing",
    "I dislike errors in the code",
]
labels = [1, 1, 0, 1, 0]  # Example binary labels: 1=positive, 0=negative

# 1. Data Preprocessing
tokenizer = Tokenizer(num_words=10000)  # Limit to top 10000 words
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

# Pad sequences to ensure uniform length
X = pad_sequences(sequences, padding='post')

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, np.array(labels), test_size=0.2, random_state=42)

# 2. Build the LSTM Model
model = Sequential()

# Optional: Using an Embedding layer if you're working with words represented as integers
model.add(Embedding(input_dim=10000, output_dim=128, input_length=X.shape[1]))

# LSTM layer
model.add(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2))

# Output layer
model.add(Dense(1, activation='sigmoid'))  # For binary classification

# 3. Compile the Model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# 4. Train the Model
model.fit(X_train, y_train, epochs=5, batch_size=32, validation_data=(X_test, y_test))

# 5. Evaluate the Model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Predictions (example)
text = ["I love programming"]
seq = tokenizer.texts_to_sequences(text)
padded_seq = pad_sequences(seq, maxlen=max_length, padding='post')
predictions = model_lstm.predict(padded_seq)

# Decode predictions
predicted_labels = label_encoder.inverse_transform((predictions > 0.5).astype(int))
print(f"LSTM Predictions: {predicted_labels}")

"""b) RNN"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
# Example Data (X: Text, y: Labels)
texts = [
    "I love programming",
    "Python is great for data science",
    "I hate bugs in the code",
    "Data science is amazing",
    "I dislike errors in the code",
]
labels = [1, 1, 0, 1, 0]  # Example binary labels: 1=positive, 0=negative

# Data Preprocessing
tokenizer = Tokenizer(num_words=10000)  # Limit to top 10000 words
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
# Pad sequences to ensure uniform length
X = pad_sequences(sequences, padding='post')

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, np.array(labels), test_size=0.2, random_state=42)

# Build the RNN Model
model = Sequential()
# Optional: Using an Embedding layer if you're working with words represented as integers
model.add(Embedding(input_dim=10000, output_dim=128, input_length=X.shape[1]))
# Simple RNN layer
model.add(SimpleRNN(units=128, dropout=0.2, recurrent_dropout=0.2))
# Output layer
model.add(Dense(1, activation='sigmoid'))  # For binary classification

# Compile and Train the Model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=6, batch_size=32, validation_data=(X_test, y_test))
# Evaluate the Model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

"""# **Experiment - 11**

**Aim**: To implement a)GLOVE b)RNTN.

(a) Glove
"""

!unzip /content/glove.6B (2).zip

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping

# Load GloVe embeddings
def load_glove_embeddings(file_path):
    embeddings_index = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            coefs = np.asarray(values[1:], dtype='float32')
            embeddings_index[word] = coefs
    return embeddings_index

# Example: Load GloVe 100D embeddings
glove_path = '/content/glove.6B.100d.txt'  # Adjust path
embeddings_index = load_glove_embeddings(glove_path)
print(f"Loaded {len(embeddings_index)} word vectors.")

# Expanded example texts and labels
texts = [
    "I love programming",
    "Python is great for data science",
    "I hate bugs in the code",
    "Data science is amazing",
    "I dislike errors in the code",
    "Coding is fun and rewarding",
    "I enjoy learning new technologies",
    "Debugging can be frustrating",
    "Errors in code make me unhappy",
    "I am passionate about machine learning"
]
labels = [1, 1, 0, 1, 0, 1, 1, 0, 0, 1]

# Tokenization and padding
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
X = pad_sequences(sequences, padding='post')
X_train, X_test, y_train, y_test = train_test_split(X, np.array(labels), test_size=0.2, random_state=42)

# Embedding matrix
embedding_dim = 100
embedding_matrix = np.zeros((len(tokenizer.word_index) + 1, embedding_dim))
for word, i in tokenizer.word_index.items():
    if word in embeddings_index:
        embedding_matrix[i] = embeddings_index[word]
print(f"Embedding matrix shape: {embedding_matrix.shape}")

# Build fine-tuned model
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index) + 1,
                    output_dim=embedding_dim,
                    weights=[embedding_matrix],
                    input_length=X.shape[1],
                    trainable=True))
model.add(Bidirectional(LSTM(units=128, dropout=0.2, recurrent_dropout=0.2, return_sequences=True)))
model.add(Bidirectional(LSTM(units=64, dropout=0.2, recurrent_dropout=0.2)))
model.add(Dense(32, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# Compile and set up early stopping
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model
model.fit(X_train, y_train, epochs=70, batch_size=16, validation_data=(X_test, y_test), callbacks=[early_stopping])

# Evaluate the model
y_pred = (model.predict(X_test) > 0.5).astype('int32')
print(classification_report(y_test, y_pred))
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

"""(b) RNTN"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Embedding, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from sklearn.metrics import classification_report

# Sample parsed data (simplified for example purposes)
tree_data = [
    {'sentence': 'I love programming', 'label': 1, 'tree': ['I', ['love', 'programming']]},
    {'sentence': 'I dislike bugs', 'label': 0, 'tree': ['I', ['dislike', 'bugs']]},
    {'sentence': 'Python is great', 'label': 1, 'tree': ['Python', ['is', 'great']]},
    {'sentence': 'I hate errors', 'label': 0, 'tree': ['I', ['hate', 'errors']]}
]

# Word Embeddings (Random Initialization)
vocab = {'I': 0, 'love': 1, 'programming': 2, 'dislike': 3, 'bugs': 4, 'Python': 5, 'is': 6, 'great': 7, 'hate': 8, 'errors': 9}
vocab_size = len(vocab)
embedding_dim = 50
embedding_matrix = np.random.rand(vocab_size, embedding_dim)

# Recursive Composition Layer (RNTN Layer)
class RNTNLayer(tf.keras.layers.Layer):
    def __init__(self, embedding_dim, **kwargs):
        super().__init__(**kwargs)
        self.embedding_dim = embedding_dim
        self.W = self.add_weight(
            shape=(embedding_dim * 2, embedding_dim * 2, embedding_dim),
            initializer='random_normal', name='W')
        self.V = self.add_weight(
            shape=(embedding_dim * 2, embedding_dim),
            initializer='random_normal', name='V')
        self.b = self.add_weight(
            shape=(embedding_dim,), initializer='zeros', name='b')

    def call(self, left, right):
        concat = tf.concat([left, right], axis=-1)  # Shape: (batch, embedding_dim*2)
        tensor_prod = tf.einsum('bi,ijk,bj->bk', concat, self.W, concat)  # Shape: (batch, embedding_dim)
        linear = tf.matmul(concat, self.V)  # Shape: (batch, embedding_dim)
        return tf.nn.tanh(tensor_prod + linear + self.b)

# Fine-tuned RNTN model with extra hidden layer and dropout
class RNTNModel(Model):
    def __init__(self, vocab_size, embedding_dim, embedding_matrix, dropout_rate=0.5, **kwargs):
        super().__init__(**kwargs)
        self.embedding = Embedding(input_dim=vocab_size, output_dim=embedding_dim,
                                   weights=[embedding_matrix], trainable=True)
        self.rntn = RNTNLayer(embedding_dim)
        # Extra dense hidden layer with L2 regularization
        self.hidden = Dense(32, activation='relu', kernel_regularizer=l2(0.01))
        # Dropout layer to reduce overfitting
        self.dropout = Dropout(dropout_rate)
        self.output_dense = Dense(1, activation='sigmoid')

    def compose_tree(self, tree):
        # If the node is a leaf (a word), return its embedding.
        if isinstance(tree, str):
            word_index = vocab.get(tree)
            if word_index is None:
                raise ValueError(f"Word '{tree}' not found in vocabulary.")
            return self.embedding(tf.constant([word_index]))  # Shape: (1, embedding_dim)
        # Otherwise, assume tree is a pair [left, right]
        left, right = tree
        left_emb = self.compose_tree(left)
        right_emb = self.compose_tree(right)
        return self.rntn(left_emb, right_emb)

    def call(self, tree):
        composed = self.compose_tree(tree)
        hidden_out = self.hidden(composed)
        dropped = self.dropout(hidden_out)
        return self.output_dense(dropped)

    def predict_tree(self, tree):
        return self.call(tree)

# Prepare training data
X_train = [item['tree'] for item in tree_data]
y_train = np.array([item['label'] for item in tree_data]).reshape(-1, 1)

# Instantiate the model and optimizer (with a lower learning rate for fine-tuning)
model = RNTNModel(vocab_size, embedding_dim, embedding_matrix, dropout_rate=0.5)
optimizer = Adam(learning_rate=0.001)

# Training loop (tree-by-tree)
epochs = 100
for epoch in range(epochs):
    losses = []
    for i, tree in enumerate(X_train):
        with tf.GradientTape() as tape:
            prediction = model.predict_tree(tree)  # Shape: (1, 1)
            loss = tf.keras.losses.binary_crossentropy(y_train[i:i+1], prediction)
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(zip(grads, model.trainable_variables))
        losses.append(loss.numpy())
    if (epoch + 1) % 10 == 0:
        print(f'Epoch {epoch+1}, Loss: {np.mean(losses):.4f}')

# Evaluate the model on training data
y_pred = []
for tree in X_train:
    pred = model.predict_tree(tree).numpy()
    y_pred.append(int(pred > 0.5))
print(classification_report(y_train, y_pred))

"""**Result** - Sucessfully implemented Glove and RNTN.

"""