# -*- coding: utf-8 -*-
"""Multimodal AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prZ_9K1TF2taXNY6AgY9indWbY79aw_W

# **Data Cleaning Using NLTK**

**Aim:** To perform text preprocessing using NLTK for cleaning, tokenizing, stopword removal, stemming, and text augmentation.

**Theory:** Natural Language Processing (NLP) requires raw text to be cleaned and standardized for better model performance.
Data cleaning involves steps like sentence/word tokenization, case normalization, punctuation removal, stopword filtering, and stemming to reduce words to their base form.
NLTK provides powerful tools for preprocessing text, while augmentation (via WordNet) enriches data by replacing words with synonyms, improving generalization in NLP models.
"""

import re
import string

!sudo pip install -U nltk

import nltk
nltk.download('all')

from nltk import sent_tokenize
# load data
filename = '/content/metamorphosis.txt'
file = open(filename, 'rt')
text = file.read()
file.close()

# split into sentences
sentences = sent_tokenize(text)
print(sentences[0])

from nltk.tokenize import word_tokenize
# split into words
tokens = word_tokenize(text)
print(tokens[:100])

# convert to lower case
tokens = [w.lower() for w in tokens]
print(tokens[:100])

# prepare regex for char filtering
re_punc = re.compile('[%s]' % re.escape(string.punctuation))
print(tokens[:100])

#filter out punctuations
stripped = [re_punc.sub(" ", w) for w in tokens]
# remove all tokens that are not alphabetic
words = [word for word in tokens if word.isalpha()]
print(words[:100])

#filter out stop words (and pipeline)
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

from nltk.stem.porter import PorterStemmer
# stemming of words
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in tokens]
print(stemmed[:100])

!pip install textattack

from textattack.augmentation import WordNetAugmenter

augmenter = WordNetAugmenter()

# Example usage:
sentence = "The quick brown fox jumps over the lazy dog."
augmented_sentence = augmenter.augment(sentence)

print(f"Original Sentence: {sentence}")
print(f"Augmented Sentence: {augmented_sentence}")

"""**Result:** The text was successfully preprocessed with tokenization, stopword removal, stemming, and augmented using WordNet to generate meaningful variations of sentences.

# **Experiment - 1**

**Aim:** Extract text embeddings (using BERT/GPT), image embeddings (using ResNet/Vision Transformer) and audio embeddings (Wav2Vec). Compare different representation techniques and visualize them using t-SNE or PCA.

**Theory:**

This experiment extracts and compares embeddings from three modalities:

**Text (BERT)**: Uses transformer-based BERT to generate contextual embeddings. The [CLS] token output represents the sentence.

**Image (ResNet50)**: CNN-based model pretrained on ImageNet. The final feature vector encodes semantic image features.

**Audio (Wav2Vec2.0)**: Transformer-based speech model that converts raw waveforms into expressive embeddings.

Since embeddings are high-dimensional, dimensionality reduction is applied:

**PCA:** Linear technique projecting data onto axes of maximum variance.

**t-SNE**: Non-linear technique preserving local neighborhood relations, useful for cluster visualization.

By plotting embeddings in 2D space, similarities and differences across modalities can be observed. This highlights how pre-trained models provide universal vector representations that make multimodal comparison and learning possible.
"""

import torch
import torchvision.transforms as transforms
from torchvision import models
from transformers import BertTokenizer, BertModel, Wav2Vec2Processor, Wav2Vec2Model
import librosa
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from PIL import Image



# Load pre-trained models
def load_models():
    text_model = BertModel.from_pretrained('bert-base-uncased')
    image_model = models.resnet50(pretrained=True)
    audio_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")
    return text_model, image_model, audio_model

# Text embedding extraction
def extract_text_embedding(text, model):
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy()

# Image embedding extraction
def extract_image_embedding(image_path, model):
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    image = Image.open(image_path).convert("RGB")
    image = transform(image).unsqueeze(0)
    with torch.no_grad():
        features = model(image)
    return features.numpy()

# Audio embedding extraction
def extract_audio_embedding(audio_path, model):
    processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
    waveform, _ = librosa.load(audio_path, sr=16000)
    inputs = processor(waveform, return_tensors="pt", sampling_rate=16000)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy()

# Dimensionality reduction and visualization
def visualize_embeddings(embeddings, method="pca", title="Visualization"):
    if method == "pca":
        reducer = PCA(n_components=2)
    else:
        reducer = TSNE(n_components=2, perplexity=1, random_state=42)
    reduced_embeddings = reducer.fit_transform(embeddings)
    plt.scatter(reduced_embeddings[:, 0], reduced_embeddings[:, 1])
    plt.title(title)
    plt.show()

# Example usage
def main():
    text_model, image_model, audio_model = load_models()

    text_embedding = extract_text_embedding("This is an example sentence.", text_model)
    image_embedding = extract_image_embedding("/content/drive/MyDrive/WhatsApp Image 2025-02-16 at 18.55.15_340f8369.jpg", image_model)
    audio_embedding = extract_audio_embedding("/content/drive/MyDrive/OAF_back_angry.wav", audio_model)
    image_embedding_trimmed = image_embedding[:, :768]


    print (text_embedding.shape)
    print (image_embedding_trimmed.shape)
    print (audio_embedding.shape)


    embeddings = np.vstack([text_embedding,image_embedding_trimmed , audio_embedding])
    visualize_embeddings(embeddings, method="pca", title="PCA Visualization of Modalities")
    visualize_embeddings(embeddings, method="tsne", title="t-SNE Visualization of Modalities")

if __name__ == "__main__":
    main()

import os
import torch
import torchvision.transforms as transforms
from torchvision import models
from transformers import BertTokenizer, BertModel, Wav2Vec2Processor, Wav2Vec2Model
import librosa
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from PIL import Image

# Load pre-trained models
def load_models():
    text_model = BertModel.from_pretrained('bert-base-uncased')
    image_model = models.resnet50(pretrained=True)
    audio_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")
    return text_model, image_model, audio_model

# Text embedding extraction
def extract_text_embedding(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy().squeeze()

# Image embedding extraction
def extract_image_embedding(image_path, model):
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    image = Image.open(image_path).convert("RGB")
    image = transform(image).unsqueeze(0)
    with torch.no_grad():
        features = model(image)
    return features.numpy().squeeze()[:768]  # Ensure 1D shape

# Audio embedding extraction
def extract_audio_embedding(audio_path, model, processor):
    waveform, _ = librosa.load(audio_path, sr=16000)
    inputs = processor(waveform, return_tensors="pt", sampling_rate=16000)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].numpy().squeeze()[:768]  # Ensure 1D shape

# Dimensionality reduction and visualization
def visualize_embeddings(embeddings, method="pca", title="Visualization"):
    if method == "pca":
        reducer = PCA(n_components=2)
    else:
        perplexity = min(30, len(embeddings) - 1)  # Ensure perplexity < n_samples
        reducer = TSNE(n_components=2, perplexity=perplexity, random_state=42)

    reduced_embeddings = reducer.fit_transform(embeddings)
    plt.scatter(reduced_embeddings[:, 0], reduced_embeddings[:, 1])
    plt.title(title)
    plt.show()

# Function to get file paths from a directory
def get_file_paths(folder_path, extensions):
    return [os.path.join(folder_path, file) for file in os.listdir(folder_path) if file.lower().endswith(extensions)]

# Example usage
def main():
    # Load models
    text_model, image_model, audio_model = load_models()
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")

    # Folder paths (UPDATE THESE)
    image_folder = "/content/drive/MyDrive/Images"  # Update with actual folder path
    audio_folder = "/content/drive/MyDrive/Audio"  # Update with actual folder path

    # Get file paths
    image_samples = get_file_paths(image_folder, ('.jpg', '.png', '.jpeg'))
    audio_samples = get_file_paths(audio_folder, ('.wav', '.mp3'))

    # Text samples (modify as needed)
    text_samples = [
        "This is the first sentence.",
        "Another example sentence.",
        "Deep learning is interesting!",
        "AI is transforming industries.",
        "Data science is amazing.",
        "The future is AI-driven.",
        "Neural networks are powerful.",
        "I love working with transformers.",
        "Computer vision is fascinating.",
        "Speech recognition is advancing rapidly."
    ]

    # Limit samples to the same number across modalities
    num_samples = min(len(text_samples), len(image_samples), len(audio_samples))
    text_samples = text_samples[:num_samples]
    image_samples = image_samples[:num_samples]
    audio_samples = audio_samples[:num_samples]

    # Extract embeddings
    text_embeddings = np.array([extract_text_embedding(text, text_model, tokenizer) for text in text_samples])
    image_embeddings = np.array([extract_image_embedding(img, image_model) for img in image_samples])
    audio_embeddings = np.array([extract_audio_embedding(audio, audio_model, processor) for audio in audio_samples])

    # Ensure 2D shape for PCA/t-SNE
    text_embeddings = np.array([t.flatten() for t in text_embeddings])
    image_embeddings = np.array([i.flatten() for i in image_embeddings])
    audio_embeddings = np.array([a.flatten() for a in audio_embeddings])

    # Stack embeddings
    embeddings = np.vstack([text_embeddings, image_embeddings, audio_embeddings])

    # Visualizations
    visualize_embeddings(embeddings, method="pca", title="PCA Visualization of Modalities")
    visualize_embeddings(embeddings, method="tsne", title="t-SNE Visualization of Modalities")

if __name__ == "__main__":
    main()

"""**Result:**
Successfully extracted multimodal embeddings. Visualization showed that different modalities produce distinct feature spaces, and similar data points cluster together, confirming the effectiveness of pretrained models.

# **Experiment - 2**

**Aim:** Extracting audio features using Librosa: Load an audio file and extract features like Mel spectograms, MFCCs and Chroma features. Visualize these features to understand how speech and music differ.

**Theory:**

Audio signals contain rich information beyond raw waveforms. To analyze and compare speech and music, we extract spectral features:

**Mel Spectrogram:** Represents frequency content over time on a perceptually motivated Mel scale, closer to human hearing.

**MFCCs (Mel-Frequency Cepstral Coefficients):** Compact features widely used in speech recognition. They summarize the spectral envelope of audio.

**Chroma Features:** Represent energy distribution across 12 pitch classes (like notes in music), making them useful for analyzing harmony and chords.

By visualizing these features:

**Speech** shows clear temporal changes in MFCCs and strong formant structures.

**Music** shows richer harmonic patterns in the Chroma features.

Thus, feature extraction helps distinguish different types of audio and forms the foundation for tasks like **speech recognition, music classification, and emotion detection.**
"""

import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np

def load_audio(audio_path):
    y, sr = librosa.load(audio_path, sr=None)
    return y, sr

def extract_features(y, sr):
    mel_spectrogram = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    chroma = librosa.feature.chroma_stft(y=y, sr=sr)

    return mel_spectrogram, mfccs, chroma

def visualize_features(mel_spectrogram, mfccs, chroma, sr):
    plt.figure(figsize=(10, 6))

    plt.subplot(3, 1, 1)
    librosa.display.specshow(librosa.power_to_db(mel_spectrogram, ref=np.max), sr=sr, x_axis='time', y_axis='mel')
    plt.colorbar()
    plt.title("Mel Spectrogram")

    plt.subplot(3, 1, 2)
    librosa.display.specshow(mfccs, sr=sr, x_axis='time')
    plt.colorbar()
    plt.title("MFCCs")

    plt.subplot(3, 1, 3)
    librosa.display.specshow(chroma, sr=sr, x_axis='time', y_axis='chroma')
    plt.colorbar()
    plt.title("Chroma Features")

    plt.tight_layout()
    plt.show()

def main():
    audio_path = "/content/OAF_back_fear.wav"
    y, sr = load_audio(audio_path)
    mel_spectrogram, mfccs, chroma = extract_features(y, sr)
    visualize_features(mel_spectrogram, mfccs, chroma, sr)

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')

"""**Result:**
The extracted features clearly distinguished between speech and music patterns. Mel spectrograms captured frequency distribution, MFCCs modeled human auditory perception, and Chroma features highlighted harmonic structures.

# **Experiment - 3**

**Aim:** Concatenation-Based Feature Fusion: Take a text description of image and its image feature, concatenate both and use a simple MLP for classification

**Theory:**

In multimodal learning, information from different sources (e.g., text and images) can be combined to improve classification tasks. A simple approach is early fusion by concatenation:

**Image Features:** Extracted from pre-trained CNNs (e.g., ResNet50) to capture visual semantics.

**Text Features:** Extracted from pre-trained transformers (e.g., BERT or Sentence Transformers) to represent captions/descriptions.

**Fusion:** The feature vectors are concatenated into a single representation.

**Classifier:** A Multi-Layer Perceptron (MLP) processes the combined features to predict the class label.

This method leverages both modalities together, improving performance compared to unimodal models. It is widely used in tasks like **image captioning, sentiment analysis with visuals, and multimodal retrieval.**
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Concatenate, Dropout
from tensorflow.keras.models import Model

image_feat_dim = 2048 # e.g., output of ResNet50 or EfficientNet
text_feat_dim = 768 # e.g., BERT embedding size
num_classes = 2 # e.g., binary classification

image_input = Input(shape=(image_feat_dim,), name='image_input')
text_input = Input(shape=(text_feat_dim,), name='text_input')

combined = Concatenate()([image_input, text_input])

# === MLP Head ===
x = Dense(512, activation='relu')(combined)
x = Dropout(0.3)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
output = Dense(num_classes, activation='softmax')(x)

# === Model ===
model = Model(inputs=[image_input, text_input], outputs=output)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

# Image features: Extracted using pretrained CNN like ResNet50
# Example: img_feat = model.predict(preprocessed_image)

# Text features: Use BERT, DistilBERT, or sentence-transformers to get text embeddings
# Example using sentence-transformers:
from sentence_transformers import SentenceTransformer
text_model = SentenceTransformer('all-MiniLM-L6-v2')
text_feat = text_model.encode(["A red fire burning in the forest"]) # returns shape (768,)

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


def load_dataset(captions_file, image_folder):
    captions = pd.read_csv(captions_file)
    image_features = extract_image_features(image_folder, captions['image'])
    text_features = extract_text_features(captions['caption'])
    labels = np.random.randint(0, 2, len(captions))  # Dummy labels for binary classification

    return text_features, image_features, labels


def extract_text_features(captions):
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    model = BertModel.from_pretrained('bert-base-uncased').to(device)
    model.eval()

    features = []
    for caption in captions:
        inputs = tokenizer(caption, return_tensors='pt', padding=True, truncation=True).to(device)
        with torch.no_grad():
            outputs = model(**inputs)
        features.append(outputs.last_hidden_state[:, 0, :].cpu().numpy())

    return np.vstack(features)


def extract_image_features(image_folder, image_filenames):
    model = models.resnet50(pretrained=True).to(device)
    model = nn.Sequential(*list(model.children())[:-1])  # Remove final classification layer
    model.eval()

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])

    features = []
    for img_name in image_filenames:
        img_path = os.path.join(image_folder, img_name)
        image = Image.open(img_path).convert("RGB")
        image = transform(image).unsqueeze(0).to(device)

        with torch.no_grad():
            feature = model(image).squeeze().cpu().numpy()
        features.append(feature)

    return np.vstack(features)


def preprocess_data(text_features, image_features, labels):
    combined_features = np.hstack((text_features, image_features))
    scaler = StandardScaler()
    combined_features = scaler.fit_transform(combined_features)
    return train_test_split(combined_features, labels, test_size=0.2, random_state=42)


class MLPClassifier(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_classes=2):
        super(MLPClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x


def train_model(model, criterion, optimizer, X_train, y_train, epochs=20):
    model.train()
    inputs = torch.tensor(X_train, dtype=torch.float32).to(device)
    labels = torch.tensor(y_train, dtype=torch.long).to(device)

    for epoch in range(epochs):
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 5 == 0:
            print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')


def evaluate_model(model, X_test, y_test):
    model.eval()
    with torch.no_grad():
        inputs = torch.tensor(X_test, dtype=torch.float32).to(device)
        outputs = model(inputs).cpu().numpy()
        predictions = np.argmax(outputs, axis=1)

    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    auc_roc = roc_auc_score(y_test, outputs[:, 1])

    print(f'Accuracy: {accuracy:.4f}, F1-score: {f1:.4f}, AUC-ROC: {auc_roc:.4f}')


def main():
    captions_file = "/content/drive/MyDrive/captions.txt/captions.txt"  # Update the path
    image_folder = "/content/drive/MyDrive/Flickr8K_images/Images"  # Update the path

    text_features, image_features, labels = load_dataset(captions_file, image_folder)
    X_train, X_test, y_train, y_test = preprocess_data(text_features, image_features, labels)
    input_size = X_train.shape[1]

    # Early Fusion Model
    early_fusion_model = MLPClassifier(input_size=input_size).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(early_fusion_model.parameters(), lr=0.001)

    print("Training Early Fusion Model...")
    train_model(early_fusion_model, criterion, optimizer, X_train, y_train)
    print("Evaluating Early Fusion Model...")
    evaluate_model(early_fusion_model, X_test, y_test)


if __name__ == "__main__":
    main()

"""**Result:**
The fusion approach improved classification performance compared to single-modality inputs. This demonstrated the effectiveness of multimodal feature integration for richer representation learning.

# **Experiment - 4**

**Aim:** Comparison of late and early fusion in multimodal classification

**Theory:**

In multimodal classification, fusion strategies determine how information from different modalities (e.g., text + image) is combined:

**Early Fusion (Feature-level fusion):**

*   Features from each modality are extracted first.
*   Then, they are concatenated into a joint representation.
*   A single classifier is trained on this combined feature space.
*   *Advantage:* Learns cross-modal interactions.
*   *Limitation:* High-dimensional inputs, sensitive to noise.


---



**Late Fusion (Decision-level fusion):**
*   Each modality is processed separately with its own classifier.
*   The outputs (predictions) are combined (e.g., averaging, voting).
*   *Advantage:* Simpler, robust to noisy modalities.
*   *Limitation:* Does not learn deep feature interactions.


---



**Comparison:**

Early fusion captures richer joint patterns but is computationally heavier.

*   Early fusion captures richer joint patterns but is computationally heavier.
*   Late fusion is more modular and interpretable but may lose synergy between modalities.

This experiment highlights how fusion choice affects performance, guiding model design in tasks like multimodal sentiment analysis, image–text retrieval, and medical diagnosis.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from PIL import Image
from torch.nn.utils.rnn import pad_sequence
import time
from collections import Counter
import string
from tqdm import tqdm

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 8
EPOCHS = 5
LEARNING_RATE = 1e-3
NUM_CLASSES = 3

IMG_DIR = "dataset/Lab 3/Images/"
CAPTIONS_FILE = "dataset/Lab 3/captions.txt"

print("Loading captions file...")
df = pd.read_csv(CAPTIONS_FILE)
df_unique = df.groupby('image').first().reset_index()
image_paths = [IMG_DIR + img for img in df_unique['image'].values]
text_descriptions = df_unique['caption'].values

def assign_label(caption):
    caption = caption.lower()
    if any(word in caption for word in ["man","woman","child","boy","girl","person","people"]):
        return 0
    elif any(word in caption for word in ["dog","cat","horse","bird","elephant","animal"]):
        return 1
    elif any(word in caption for word in ["car","bus","truck","bike","bicycle","airplane","vehicle"]):
        return 2
    else:
        return 0

labels = [assign_label(c) for c in text_descriptions]

def simple_tokenizer(text):
    text = text.lower()
    text = ''.join([char for char in text if char not in string.punctuation])
    words = text.split()
    return words

def build_vocab(texts):
    counter = Counter()
    for text in texts:
        words = simple_tokenizer(text)
        counter.update(words)
    vocab = {word: idx + 1 for idx, (word, _) in enumerate(counter.most_common())}
    vocab['<PAD>'] = 0
    return vocab

class MultimodalDataset(Dataset):
    def __init__(self, image_paths, texts, labels, image_transform=None, tokenizer=None, vocab=None):
        self.image_paths = image_paths
        self.texts = texts
        self.labels = labels
        self.image_transform = image_transform or transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor()
        ])
        self.tokenizer = tokenizer
        self.vocab = vocab
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        image = Image.open(self.image_paths[idx]).convert("RGB")
        image = self.image_transform(image)
        text = self.texts[idx]
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        text_tokens = self.tokenizer(text)
        text_tensor = torch.tensor([self.vocab.get(word, self.vocab['<PAD>']) for word in text_tokens], dtype=torch.long)
        return image, text_tensor, label

def multimodal_collate_fn(batch):
    images, texts, labels = zip(*batch)
    images = torch.stack(images)
    labels = torch.tensor(labels, dtype=torch.long)
    padded_texts = pad_sequence(texts, batch_first=True, padding_value=0)
    return images, padded_texts, labels

print("Splitting train/test...")
train_paths, test_paths, train_texts, test_texts, train_labels, test_labels = train_test_split(
    image_paths, text_descriptions, labels, test_size=0.2, random_state=42)

print("Building vocabulary...")
start = time.time()
vocab = build_vocab(train_texts)
print(f"Vocabulary size: {len(vocab)} | Time: {time.time()-start:.2f}s")

train_dataset = MultimodalDataset(train_paths, train_texts, train_labels, tokenizer=simple_tokenizer, vocab=vocab)
test_dataset = MultimodalDataset(test_paths, test_texts, test_labels, tokenizer=simple_tokenizer, vocab=vocab)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=multimodal_collate_fn)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, collate_fn=multimodal_collate_fn)

class ImageEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = models.resnet50(pretrained=True)
        self.model.fc = nn.Identity()
    def forward(self, x):
        return self.model(x)

class TextEncoder(nn.Module):
    def __init__(self, vocab_size, embedding_dim=100, hidden_dim=256, num_layers=2, dropout=0.5):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, hidden_dim)
        self.dropout = nn.Dropout(dropout)
    def forward(self, text):
        embedded = self.embedding(text)
        lstm_out, (h, c) = self.lstm(embedded)
        output = self.fc(self.dropout(h[-1]))
        return output

class EarlyFusion(nn.Module):
    def __init__(self, num_classes, vocab_size):
        super().__init__()
        self.image_encoder = ImageEncoder()
        self.text_encoder = TextEncoder(vocab_size)
        self.classifier = nn.Sequential(
            nn.Linear(2048 + 256, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, num_classes)
        )
    def forward(self, image, text):
        img_feat = self.image_encoder(image)
        txt_feat = self.text_encoder(text)
        combined = torch.cat((img_feat, txt_feat), dim=1)
        return self.classifier(combined)

class LateFusion(nn.Module):
    def __init__(self, num_classes, vocab_size):
        super().__init__()
        self.image_encoder = ImageEncoder()
        self.text_encoder = TextEncoder(vocab_size)
        self.img_classifier = nn.Linear(2048, num_classes)
        self.txt_classifier = nn.Linear(256, num_classes)
    def forward(self, image, text):
        img_feat = self.image_encoder(image)
        txt_feat = self.text_encoder(text)
        img_pred = self.img_classifier(img_feat)
        txt_pred = self.txt_classifier(txt_feat)
        return (img_pred + txt_pred) / 2

def train_model(model, train_loader):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    for epoch in range(EPOCHS):
        model.train()
        epoch_start = time.time()
        loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}", leave=False)
        for images, texts, labels in loop:
            images, texts, labels = images.to(DEVICE), texts.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(images, texts)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            loop.set_postfix(loss=loss.item())
        print(f"Epoch {epoch+1} finished in {time.time()-epoch_start:.2f}s | Loss: {loss.item():.4f}")

def evaluate_model(model, test_loader):
    print("Evaluating model...")
    start = time.time()
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, texts, labels in tqdm(test_loader, desc="Testing"):
            images, texts, labels = images.to(DEVICE), texts.to(DEVICE), labels.to(DEVICE)
            outputs = model(images, texts)
            all_preds.extend(torch.softmax(outputs, 1).cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)
    acc = accuracy_score(all_labels, all_preds.argmax(1))
    f1 = f1_score(all_labels, all_preds.argmax(1), average='weighted')
    auc = roc_auc_score(all_labels, all_preds, multi_class='ovo', labels=list(range(NUM_CLASSES)))
    print(f"Evaluation finished in {time.time()-start:.2f}s")
    print("Classification Report:\n", classification_report(all_labels, all_preds.argmax(1)))
    cm = confusion_matrix(all_labels, all_preds.argmax(1))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()
    return {'accuracy': acc, 'f1_score': f1, 'auc_roc': auc}

if __name__ == "__main__":
    vocab_size = len(vocab)
    early_fusion = EarlyFusion(NUM_CLASSES, vocab_size).to(DEVICE)
    train_model(early_fusion, train_loader)
    early_results = evaluate_model(early_fusion, test_loader)
    late_fusion = LateFusion(NUM_CLASSES, vocab_size).to(DEVICE)
    train_model(late_fusion, train_loader)
    late_results = evaluate_model(late_fusion, test_loader)
    results_df = pd.DataFrame({'Early Fusion': early_results, 'Late Fusion': late_results}).T
    print("\nModel Comparison:")
    print(results_df)

"""**Result:**
Early fusion captured deeper cross-modal interactions, giving slightly higher accuracy, while late fusion was simpler and more robust to noisy inputs. The experiment highlighted trade-offs between performance and interpretability in fusion strategies.

# **Experiment - 5**

**Aim:** Image to text retrieval using clip. Load Open AI clip modal and input an image retrieve the most relevant text captions from a dataset and try to reverse ie given the text description and retrieve the most similar image.

**Theory:**

Image-to-text retrieval and text-to-image retrieval are tasks where models match one modality with the other:

**CLIP (Contrastive Language–Image Pretraining):**
*   Trained on 400M image–text pairs.
*   Learns a joint embedding space where semantically similar images and captions are close.
*   Uses dual encoders:
1.   Vision Transformer (ViT) for images
2.   Transformer for text
**How retrieval works:**
*   Convert images and text into embeddings using CLIP.
*   Normalize embeddings to unit length.
*   Compute similarity (dot product or cosine).
*   Retrieve the top-k most similar matches.
*   **Image →** Text Retrieval: Input an image, find best-matching captions.
*   **Text →** Image Retrieval: Input a caption, find best-matching images.

**Applications:**
*   Image search engines (Google Images, Pinterest).
*   Multimodal assistants (captioning, visual Q&A).
*   Content moderation (detect mismatched or harmful media).
"""

pip install torch torchvision transformers pillow faiss-cpu

pip install git+https://github.com/openai/CLIP.git

import torch
import clip
from PIL import Image
import faiss

# Load CLIP model
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = clip.load("ViT-B/32", device=device)

# Image ↔ Text Retrieval with CLIP (HuggingFace)
import torch
from transformers import CLIPProcessor, CLIPModel
from PIL import Image

# Step 1: Load Model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# Step 2: Define Dataset
# Example dataset (replace with your own paths + captions)
captions = [
    "a dog playing in the park",
    "a man riding a bicycle",
    "a cat sleeping on the sofa"
]

images = [
    "/content/dog.jpg",
    "/content/bike.jpg",
    "/content/cat.jpg"
]

# Step 3: Encode Text Captions
text_inputs = processor(text=captions, return_tensors="pt", padding=True).to(device)
with torch.no_grad():
    text_embeddings = model.get_text_features(**text_inputs)
text_embeddings = text_embeddings / text_embeddings.norm(p=2, dim=-1, keepdim=True)

# Step 4: Encode Images
image_embeddings = []
for img_path in images:
    image = Image.open(img_path)
    inputs = processor(images=image, return_tensors="pt").to(device)
    with torch.no_grad():
        emb = model.get_image_features(**inputs)
    emb = emb / emb.norm(p=2, dim=-1, keepdim=True)
    image_embeddings.append(emb)

image_embeddings = torch.cat(image_embeddings, dim=0)

# Step 5: Retrieval Functions
def retrieve_text_from_image(query_img, top_k=3):
    """Given an image, return top-k matching captions"""
    image = Image.open(query_img)
    inputs = processor(images=image, return_tensors="pt").to(device)
    with torch.no_grad():
        query_emb = model.get_image_features(**inputs)
    query_emb = query_emb / query_emb.norm(p=2, dim=-1, keepdim=True)

    sims = (query_emb @ text_embeddings.T).squeeze(0)
    topk = torch.topk(sims, k=top_k)
    return [captions[i] for i in topk.indices], topk.values.tolist()

def retrieve_image_from_text(query_text, top_k=3):
    """Given a text query, return top-k matching images"""
    inputs = processor(text=[query_text], return_tensors="pt", padding=True).to(device)
    with torch.no_grad():
        query_emb = model.get_text_features(**inputs)
    query_emb = query_emb / query_emb.norm(p=2, dim=-1, keepdim=True)

    sims = (query_emb @ image_embeddings.T).squeeze(0)
    topk = torch.topk(sims, k=top_k)
    return [images[i] for i in topk.indices], topk.values.tolist()

# Step 6: Example Queries
# Image → Text
captions_found, scores = retrieve_text_from_image("dog.jpg")
print("\nImage → Text Retrieval")
for cap, sc in zip(captions_found, scores):
    print(f"{cap} (score: {sc:.4f})")

# Text → Image
images_found, scores = retrieve_image_from_text("a man riding a bicycle")
print("\nText → Image Retrieval")
for img, sc in zip(images_found, scores):
    print(f"{img} (score: {sc:.4f})")

# Example Queries using the defined functions
# Assuming you have images named 'dog.jpg', 'bike.jpg', and 'cat.jpg' in the '/content/' directory

# Image -> Text retrieval
query_image_path = "/content/dog.jpg"
top_k_captions = retrieve_text_from_image(query_image_path, top_k=2)
print(f"Top 2 captions for {query_image_path}: {top_k_captions}")

# Text -> Image retrieval
query_text = "a cat"
top_k_images = retrieve_image_from_text(query_text, top_k=2)
print(f"Top 2 images for text query '{query_text}': {top_k_images}")

"""**Result:**
The CLIP model successfully retrieved semantically relevant matches in both directions (image→text and text→image). This validated CLIP’s strength in learning a shared embedding space for vision and language.

# **Experiment - 6**

**Aim:** Evaluating an image captioning model. Generate caption using an image captioning model and compare with ground truth caption by evaluating BLEU, ROUGE and METEOR scores for text simmilarity and BERT score for semantic simmilarity.

**Theory:**

Image Captioning models generate natural language descriptions for images. Evaluating these captions requires comparing them with human-written references. Different metrics capture different aspects of quality:

**BLEU (Bilingual Evaluation Understudy):** Measures n-gram overlap between generated and reference captions. Higher BLEU indicates closer word-level similarity.

**ROUGE (Recall-Oriented Understudy for Gisting Evaluation):** Focuses on recall of overlapping words/phrases. Often used in summarization tasks, but effective for captions too.

**METEOR (Metric for Evaluation of Translation with Explicit ORdering):** Considers synonymy, stemming, and word order, giving a more nuanced similarity score.

**BERTScore:** Uses contextual embeddings from BERT to measure semantic similarity between generated and ground-truth captions. Unlike lexical metrics, it captures meaning even if wording differs.


By combining these metrics, we can evaluate both surface similarity (BLEU, ROUGE, METEOR) and semantic closeness (BERTScore).
"""

!pip install rouge-score nltk bert-score

import nltk
nltk.download('wordnet')
nltk.download('punkt')

# Imports
from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score
from bert_score import score as bert_score

# Image Captioning Evaluation
# Metrics: ROUGE, METEOR, BERTScore


# Install dependencies if not already installed
# !pip install rouge-score nltk bert-score
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
smooth_fn = SmoothingFunction().method1
from rouge_score import rouge_scorer
from nltk.translate.meteor_score import meteor_score
from bert_score import score as bert_score

# Step 1: Example Captions
generated_captions = [
    "A dog is plays with a ball in the park outside",
    "Two men are sitting at a table eating food",
    "A group of people are standing near a bus stop",
    "Two men are sitting on a bench"
]

# Ground truth human-annotated captions
ground_truth_captions = [
    "A dog plays with a ball outside",
    "Two men are eating food at the table",
    "Several people are waiting near the bus stop",
    "Two men sit on a bench"
]

# Step 2: Initialize Metrics
scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
all_bleu = []
all_rouge = []
all_meteor = []
all_bert_f1 = []

# Step 3: Evaluate Each Pair
for gen, gt in zip(generated_captions, ground_truth_captions):
    print("\nGenerated:", gen)
    print("Ground Truth:", gt)

    # BLEU
    bleu = sentence_bleu([gt.split()], gen.split(), smoothing_function=smooth_fn)
    print("BLEU:", bleu)
    all_bleu.append(bleu)

    # ROUGE
    rouge_scores = scorer.score(gt, gen)
    print("ROUGE:", rouge_scores)
    all_rouge.append(rouge_scores)

    # METEOR
    meteor = meteor_score([gt.split()], gen.split())
    print("METEOR:", meteor)
    all_meteor.append(meteor)

# BERTScore (batch evaluation supported natively)
P, R, F1 = bert_score(generated_captions, ground_truth_captions, lang="en", verbose=True)
all_bert_f1 = F1.tolist()

# Step 4: Show Results
print("\n================ Final Results ================")

# BLEU
avg_bleu = sum(all_bleu) / len(all_bleu)
print(f"Average BLEU: {avg_bleu:.4f}")

# ROUGE (average across captions)
avg_rouge1 = sum([r['rouge1'].fmeasure for r in all_rouge]) / len(all_rouge)
avg_rouge2 = sum([r['rouge2'].fmeasure for r in all_rouge]) / len(all_rouge)
avg_rougeL = sum([r['rougeL'].fmeasure for r in all_rouge]) / len(all_rouge)
print(f"Average ROUGE-1: {avg_rouge1:.4f}")
print(f"Average ROUGE-2: {avg_rouge2:.4f}")
print(f"Average ROUGE-L: {avg_rougeL:.4f}")

# METEOR
avg_meteor = sum(all_meteor) / len(all_meteor)
print(f"Average METEOR: {avg_meteor:.4f}")

# BERTScore
avg_bert_f1 = sum(all_bert_f1) / len(all_bert_f1)
print(f"Average BERTScore (F1): {avg_bert_f1:.4f}")

"""**Result:** The image captioning model showed good alignment with human captions, achieving balanced BLEU, ROUGE, METEOR, and high BERTScore values, indicating both lexical and semantic similarity.

# **Experiment-7**

**Aim:** Explore the impact of various data augmentation techniques on performance of multimodal AI models.

**Theory:**

The primary goal of this experiment is to investigate the impact of data augmentation techniques on the performance of multimodal AI models, particularly for image captioning. Multimodal models, such as BLIP (Bootstrapped Language-Image Pretraining), are designed to understand and connect information across different modalities—in this case, visual content and natural language. The accuracy of such models depends not only on their architecture but also on the richness and diversity of the training data.

Data augmentation is a widely used approach to artificially expand the diversity of the dataset. By applying transformations like horizontal flipping, random rotations, and color adjustments, models are exposed to multiple variations of the same image. This enables them to handle changes in orientation, lighting, and appearance, making the model more robust to real-world conditions. In this experiment, a small dataset consisting of images paired with descriptive captions is used to illustrate the effect of augmentation.

Two evaluation scenarios are considered: one using the original images as input (baseline) and the other using augmented images. Each image is processed through the BLIP model, which generates captions describing the visual content. The predicted captions are then compared with the ground-truth captions using the BLEU score, a standard metric for evaluating the similarity between generated and reference text. Higher BLEU scores indicate that the model produces captions closer to the actual descriptions.

By comparing the average BLEU scores from the baseline and augmented scenarios, we can evaluate whether data augmentation improves the model’s generalization ability. This experiment demonstrates that even simple image transformations can significantly enhance the robustness, reliability, and accuracy of multimodal AI systems, highlighting the importance of data diversity in modern AI training pipelines.
"""

import os, random, torch, nltk
import pandas as pd
from PIL import Image
from datasets import Dataset
from transformers import BlipProcessor, BlipForConditionalGeneration
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from torchvision import transforms

# Download NLTK requirements
nltk.download("punkt")

# 1. Dataset (mini example)
# Create a small CSV: image path + caption
data = {
    "image": [
        "/content/boy holding umbrella.jpeg",
        "/content/cat-eating-out-of-food-bowl.jpg",
        "/content/french-bulldog-running.jpg"
    ],
    "caption": [
        "A boy wearing a yellow raincoat holding an umbrella",
        "A cat eating food from the bowl on the floor",
        "A dog running on a field of grass"
    ]
}
df = pd.DataFrame(data)

# Convert to HuggingFace Dataset
dataset = Dataset.from_pandas(df)

# 2. Model & Processor
device = "cuda" if torch.cuda.is_available() else "cpu"
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)

# 3. Data Augmentation
augmentations = transforms.Compose([
    transforms.RandomHorizontalFlip(p=1.0),  # always flip
    transforms.RandomRotation(30),           # random rotation
    transforms.ColorJitter(brightness=0.4, contrast=0.4)  # color change
])

def apply_augmentation(image):
    return augmentations(image)

# 4. Evaluation function
smoothie = SmoothingFunction().method4

def evaluate(dataset, use_aug=False):
    results = []
    for sample in dataset:
        image = Image.open(sample["image"]).convert("RGB")
        if use_aug:
            image = apply_augmentation(image)

        inputs = processor(images=image, return_tensors="pt").to(device)
        output = model.generate(**inputs, max_length=30)
        pred = processor.decode(output[0], skip_special_tokens=True)

        bleu = sentence_bleu([sample["caption"].split()], pred.split(), smoothing_function=smoothie)
        results.append(bleu)
        print(f"GT: {sample['caption']} | Pred: {pred} | BLEU: {bleu:.3f}")
    return sum(results) / len(results)

# 5. Run Baseline vs Augmented
print("\n---- Without Augmentation ----")
bleu_base = evaluate(dataset, use_aug=False)

print("\n---- With Augmentation ----")
bleu_aug = evaluate(dataset, use_aug=True)

print("\nAverage BLEU Without Augmentation:", bleu_base)
print("Average BLEU With Augmentation:", bleu_aug)

"""# **Experiment-8**

**Aim:** Evaluating Speech-to-Text Models: Transcribe an audio file using Whisper or Wav2Vec. Compare output with ground truth using: Word Error Rate (WER) and Levenshtein Distance (edit distance).

**Theory:**

Speech-to-Text (STT) systems convert spoken language into written text, widely used in transcription, virtual assistants, and accessibility tools. In this experiment, we use OpenAI’s Whisper model to transcribe audio generated from sample sentences and evaluate its accuracy.

Audio is prepared by converting text to speech using gTTS and optionally adding background noise to simulate real-world conditions. The transcribed output is compared with the original sentences (ground truth) using two metrics:

Word Error Rate (WER): Measures errors at the word level, accounting for insertions, deletions, and substitutions. Lower WER indicates better performance.

Levenshtein Distance: Measures character-level differences, representing the minimum edits needed to match the predicted text with the ground truth.

Both texts are normalized (lowercased, punctuation removed) to avoid trivial mismatches. Finally, results are visualized with line plots showing WER and Levenshtein distance for each sentence, along with average values. This evaluation helps assess transcription accuracy and model robustness under noisy conditions.
"""

# Install dependencies
!pip install transformers datasets jiwer soundfile torchaudio openai-whisper python-Levenshtein matplotlib

# Imports
import torch
import torchaudio
import whisper
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
import jiwer
import Levenshtein
import matplotlib.pyplot as plt

# Audio files and ground truths
AUDIO_FILES = [
    "/content/fox.opus",
    "/content/books rainy days.opus",
    "/content/ai.opus",
    "/content/sunny morning.opus",
    "/content/ripe mango.opus",
    "/content/seashell.opus",
    "/content/music.opus",
    "/content/market.opus",
    "/content/meditation.opus",
    "/content/cat.opus",
    "/content/travel.opus"
]

GROUND_TRUTHS = [
    "The quick brown fox jumps over the lazy dog",
    "I love reading books on rainy days",
    "Artificial Intelligence is changing the world",
    "Today is a beautiful sunny morning",
    "My favorite fruit is a ripe mango",
    "She sells seashells by the seashore",
    "Music can soothe the soul deeply",
    "He went to the market to buy vegetables",
    "Meditation helps reduce stress",
    "The cat is sleeping on the sofa",
    "Travel opens up your mind to new cultures"
]

# Evaluation function
def evaluate_metrics(predicted, reference):
    wer = jiwer.wer(reference.lower(), predicted.lower())
    lev_dist = Levenshtein.distance(reference.lower(), predicted.lower())
    return wer, lev_dist

# Load models once
print("🔹 Loading Whisper model...")
whisper_model = whisper.load_model("base")

print("🔹 Loading Wav2Vec2 model...")
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
wav2vec_model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

# Store results
whisper_wer_scores = []
whisper_lev_distances = []

wav2vec_wer_scores = []
wav2vec_lev_distances = []

# Loop over audio files
for i, audio_file in enumerate(AUDIO_FILES):
    print(f"\n🔸 Processing file {i+1}/{len(AUDIO_FILES)}: {audio_file}")

    # --- Whisper ---
    result = whisper_model.transcribe(audio_file)
    whisper_text = result["text"]
    wer, lev = evaluate_metrics(whisper_text, GROUND_TRUTHS[i])
    whisper_wer_scores.append(wer)
    whisper_lev_distances.append(lev)
    print("Whisper transcription:", whisper_text)

    # --- Wav2Vec2 ---
    speech_array, sampling_rate = torchaudio.load(audio_file)
    resampler = torchaudio.transforms.Resample(sampling_rate, 16000)
    speech = resampler(speech_array).squeeze().numpy()

    inputs = processor(speech, sampling_rate=16000, return_tensors="pt", padding=True)
    with torch.no_grad():
        logits = wav2vec_model(inputs.input_values).logits

    pred_ids = torch.argmax(logits, dim=-1)
    wav2vec_text = processor.decode(pred_ids[0])
    wer, lev = evaluate_metrics(wav2vec_text, GROUND_TRUTHS[i])
    wav2vec_wer_scores.append(wer)
    wav2vec_lev_distances.append(lev)
    print("Wav2Vec2 transcription:", wav2vec_text)

# Print results
print("\n✅ All results computed!")
print("Whisper WERs:", whisper_wer_scores)
print("Whisper Levenshtein distances:", whisper_lev_distances)
print("Wav2Vec2 WERs:", wav2vec_wer_scores)
print("Wav2Vec2 Levenshtein distances:", wav2vec_lev_distances)

# Line Plot results
plt.figure(figsize=(12,5))

# WER comparison line graph
plt.subplot(1,2,1)
plt.plot(range(len(AUDIO_FILES)), whisper_wer_scores, marker='o', label="Whisper", linestyle='-')
plt.plot(range(len(AUDIO_FILES)), wav2vec_wer_scores, marker='x', label="Wav2Vec2", linestyle='--')
plt.xticks(range(len(AUDIO_FILES)), [f"File{i+1}" for i in range(len(AUDIO_FILES))], rotation=45)
plt.ylabel("WER")
plt.title("Word Error Rate Comparison")
plt.legend()
plt.grid(True)

# Levenshtein distance line graph
plt.subplot(1,2,2)
plt.plot(range(len(AUDIO_FILES)), whisper_lev_distances, marker='o', label="Whisper", linestyle='-')
plt.plot(range(len(AUDIO_FILES)), wav2vec_lev_distances, marker='x', label="Wav2Vec2", linestyle='--')
plt.xticks(range(len(AUDIO_FILES)), [f"File{i+1}" for i in range(len(AUDIO_FILES))], rotation=45)
plt.ylabel("Levenshtein Distance")
plt.title("Levenshtein Distance Comparison")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Plot results
plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.bar(range(len(AUDIO_FILES)), whisper_wer_scores, alpha=0.7, label="Whisper")
plt.bar(range(len(AUDIO_FILES)), wav2vec_wer_scores, alpha=0.7, label="Wav2Vec2")
plt.xticks(range(len(AUDIO_FILES)), [f"File{i+1}" for i in range(len(AUDIO_FILES))], rotation=45)
plt.ylabel("WER")
plt.title("Word Error Rate Comparison")
plt.legend()

plt.subplot(1,2,2)
plt.bar(range(len(AUDIO_FILES)), whisper_lev_distances, alpha=0.7, label="Whisper")
plt.bar(range(len(AUDIO_FILES)), wav2vec_lev_distances, alpha=0.7, label="Wav2Vec2")
plt.xticks(range(len(AUDIO_FILES)), [f"File{i+1}" for i in range(len(AUDIO_FILES))], rotation=45)
plt.ylabel("Levenshtein Distance")
plt.title("Levenshtein Distance Comparison")
plt.legend()

plt.tight_layout()
plt.show()

"""**Result:**

# **Experiment-9**

**Aim:** Text-Based face search: Use FaceNet or Dlib to extract facial embeddings. Input a text description like *"smiling person with glasses"* and rank images based on cosine similarities.

**Theory:**

The purpose of this experiment is to explore how facial recognition embeddings can be combined with descriptive text queries to enable text-based face search. Traditional face recognition systems rely on visual-to-visual comparisons, where an input image is compared with stored face embeddings. In contrast, text-based face search aims to retrieve relevant images using natural language descriptions, such as “smiling person with glasses.” This approach bridges computer vision and natural language processing, making face retrieval more flexible and user-friendly.

Face embeddings are compact vector representations of facial features extracted using models such as FaceNet or Dlib. These embeddings capture key identity-related attributes (like facial structure, nose shape, and eye distance) in a high-dimensional space. Images of the same person produce embeddings that are close together, while different individuals’ embeddings are farther apart. Cosine similarity is typically used to measure this closeness, as it reflects the angular distance between vectors rather than their absolute magnitudes.

To integrate text descriptions into the search process, the textual query must be converted into an embedding as well. This can be done using language models or multimodal encoders trained to map text and image features into a shared embedding space. Once both text and face images are represented as vectors, similarity scores can be computed, and the images can be ranked based on how well they match the query.

This methodology enables more intuitive searching in scenarios where the user lacks an example image but can describe the target. Applications include security systems, photo organization, and multimedia retrieval, highlighting the importance of multimodal learning in real-world AI solutions.
"""

import pandas as pd
import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from transformers import CLIPProcessor, CLIPModel
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm

import zipfile
import os
from tqdm.auto import tqdm # Use tqdm.auto for better compatibility

def unzip_celeba_images(zip_path, extract_to_path):
    """
    Unzips the CelebA image archive to a specified directory.

    :param zip_path: The full path to the compressed .zip file.
    :param extract_to_path: The target directory for extracted files.
    """
    if not os.path.exists(zip_path):
        print(f"Error: Zip file not found at {zip_path}")
        return

    # Create the extraction directory if it doesn't exist
    os.makedirs(extract_to_path, exist_ok=True)

    print(f"Starting extraction of {zip_path} to {extract_to_path}...")

    try:
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            # Get the list of files for progress tracking
            file_list = zip_ref.namelist()

            if file_list:
                print(f"Found {len(file_list)} files in the archive. This may take a few minutes.")

                # Extract all members with a progress bar using tqdm
                for member in tqdm(file_list, desc="Extracting files"):
                    zip_ref.extract(member, extract_to_path)

                print("Extraction complete. Images are now available.")
            else:
                print("Warning: Zip file is empty.")

    except Exception as e:
        print(f"An error occurred during extraction: {e}")

# --- Configuration ---
# 1. The actual path you provided
ZIP_FILE_PATH = "/content/img_align_celeba.zip"

# 2. The new directory where the images will be extracted
EXTRACT_DIR = "/content/extracted_celeba_images"

# --- Execute Unzip ---
unzip_celeba_images(ZIP_FILE_PATH, EXTRACT_DIR)

# IMPORTANT: After running this, update the IMAGE_FOLDER variable in Experiment 9's
# code to point to the new location:
# IMAGE_FOLDER = "/content/extracted_celeba_images/img_align_celeba"
# Note: The extracted folder often contains a sub-folder with the same name as the zip content,
# so you might need to adjust the final path based on what's inside EXTRACT_DIR.

# --- Configuration (UPDATE PATHS if not in Kaggle) ---
# Assuming a subset of the CelebA dataset is available
ATTR_CSV_PATH = "/content/list_attr_celeba.csv"
IMAGE_FOLDER = "/content/img_align_celeba.zip"
QUERY = "smiling face with glasses"
K_TOP = 10
MAX_SAMPLES = 100

# --- Load Model and Processor ---
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

# --- Load Attribute CSV and Image List ---
attr_df = pd.read_csv(ATTR_CSV_PATH)
# Ensure the index is the image filename
attr_df = attr_df.set_index(attr_df.columns[0])

# Get a list of image file paths, filtered by the CSV index
all_image_filenames = os.listdir(IMAGE_FOLDER)
all_image_paths = [os.path.join(IMAGE_FOLDER, f) for f in all_image_filenames if f in attr_df.index]
image_files = all_image_paths[:min(MAX_SAMPLES, len(all_image_paths))]
print(f"Loaded {len(image_files)} image samples.")

# --- Functions for Metrics ---
def precision_at_k(pred_indices, relevance, k):
    """Fraction of relevant images in the top-K retrieved results."""
    if k == 0 or len(relevance) == 0: return 0.0
    k_indices = pred_indices[:k]
    return relevance[k_indices].sum() / k

def recall_at_k(pred_indices, relevance, k):
    """Fraction of all relevant images retrieved within the top-K results."""
    total_rel = relevance.sum()
    if total_rel == 0: return 0.0
    k_indices = pred_indices[:k]
    return relevance[k_indices].sum() / total_rel

def mean_average_precision(pred_indices, relevance, k):
    """Computes Mean Average Precision (mAP) for a single query (Average Precision)."""
    total_rel = relevance.sum()
    if total_rel == 0: return 0.0

    score = 0.0
    cum_rel = 0
    for i in range(k):
        if relevance[pred_indices[i]] == 1:
            cum_rel += 1
            score += cum_rel / (i + 1)
    return score / total_rel

# --- Generate Image Embeddings ---
image_embeddings = []
# Keep track of the file names for the loaded images
loaded_image_files = []
for path in tqdm(image_files, desc="Encoding Images"):
    try:
        img = Image.open(path).convert("RGB")
        inputs = processor(images=img, return_tensors="pt").to(device)
        with torch.no_grad():
            emb = model.get_image_features(**inputs)
            # L2 Normalization
            emb = emb / emb.norm(p=2, dim=-1, keepdim=True)
            image_embeddings.append(emb.cpu().numpy().squeeze())
            loaded_image_files.append(os.path.basename(path))
    except Exception as e:
        print(f"Skipping corrupt image {path}: {e}")
        continue

image_embeddings = np.vstack(image_embeddings)
image_files_map = {os.path.basename(p): p for p in image_files} # Map filename back to full path

# --- Encode Text Query ---
inputs = processor(text=[QUERY], return_tensors="pt").to(device)
with torch.no_grad():
    text_emb = model.get_text_features(**inputs)
    # L2 Normalization
    text_emb = text_emb / text_emb.norm(p=2, dim=-1, keepdim=True)
text_emb = text_emb.cpu().numpy()

# --- Compute Similarities & Top-K Retrieval ---
similarities = cosine_similarity(text_emb, image_embeddings)[0]
# argsort()[-K_TOP:] gets indices of top K_TOP similarities, [::-1] reverses to descending order
top_k_indices = similarities.argsort()[-K_TOP:][::-1]

# --- Build Ground Truth Relevance Vector ---
relevance = []
for filename in loaded_image_files:
    row = attr_df.loc[filename]
    is_relevant = (row.get("Smiling", -1) == 1) and (row.get("Eyeglasses", -1) == 1)
    relevance.append(int(is_relevant))
relevance = np.array(relevance)
print(f"Total relevant images in subset: {relevance.sum()}")

# --- Compute Metrics ---
p5 = precision_at_k(top_k_indices, relevance, 5)
r5 = recall_at_k(top_k_indices, relevance, 5)
map10 = mean_average_precision(top_k_indices, relevance, 10)

print("\n--- Retrieval Evaluation ---")
print(f"Query: {QUERY}")
print(f"Precision@5 = {p5:.4f}")
print(f"Recall@5 = {r5:.4f}")
print(f"mAP@10 = {map10:.4f}")

# --- Show Top Results ---
print("\nTop retrieved images + scores + relevance:")
fig, axes = plt.subplots(1, 5, figsize=(20, 5))
for i, idx in enumerate(top_k_indices[:5]):
    imgname = loaded_image_files[idx]

    print(f"Rank {i+1}: {imgname} | Score = {similarities[idx]:.4f} | Relevant = {relevance[idx]}")

    img_path = image_files_map[imgname]
    img = Image.open(img_path).convert("RGB")
    axes[i].imshow(img)
    axes[i].axis("off")
    axes[i].set_title(f"Rank {i+1}\nScore: {similarities[idx]:.2f}\nRel={relevance[idx]}")

plt.suptitle("Top 5 Image Retrieval Results for Query: 'smiling face with glasses'")
plt.show()

"""# **Experiment - 10**

**Aim:** Use a pre-trained VQA model to answer questions about images and evaluate its performance on a small dataset.

**Theory:**

Visual Question Answering (VQA) is a multimodal task that requires a model to understand an image and a natural language question about it, then generate an accurate, relevant answer. This task involves deep cross-modal reasoning, combining computer vision and natural language processing.

A modern, pre-trained VQA model, such as ViLT (Vision-and-Language Transformer), achieves this by moving away from complex, multi-stage architectures. Instead of processing the image (via a heavy CNN feature extractor) and the text separately before a fusion step, ViLT uses a unified, single-stream Transformer architecture.

In ViLT's approach, image patches (visual tokens) and question words (linguistic tokens) are directly embedded into a shared vector space. These interleaved tokens are fed together into a standard Transformer block, allowing the model to efficiently learn deep, joint token-level relationships right from the start. This early and joint fusion simplifies the architecture and speeds up inference while maintaining high accuracy, proving it's an efficient method for cross-modal reasoning. The model's performance is evaluated by comparing its predicted answers to the ground-truth responses.
"""

import torch
from transformers import ViltProcessor, ViltForQuestionAnswering
from PIL import Image
import os
from IPython.display import display

# --- Configuration (UPDATE PATHS) ---
IMAGE_DIR = "./sample_vqa_images/" # Placeholder for your image directory

# --- Define a small dataset (image_path, question, true_answer) ---
dataset = [
    (os.path.join(IMAGE_DIR, "/content/blue-car.webp"), "What color is the car?", "blue"),
    (os.path.join(IMAGE_DIR, "/content/husky_dog.avif"), "What is shown in the picture?", "dog"),
    (os.path.join(IMAGE_DIR, "/content/daytime_mountain.jpg"), "Is it daytime or nighttime?", "daytime"),
]

# --- Load Model and Processor ---
# The dandelin/vilt-b32-finetuned-vqa model is used
processor = ViltProcessor.from_pretrained("dandelin/vilt-b32-finetuned-vqa")
model = ViltForQuestionAnswering.from_pretrained("dandelin/vilt-b32-finetuned-vqa")

# --- Prediction Function ---
def vqa_predict(image_path, question):
    """Generates an answer for a question about an image using the VQA model."""
    try:
        image = Image.open(image_path).convert("RGB")
    except FileNotFoundError:
        print(f"Error: Image not found at {image_path}. Skipping.")
        return None
    except Exception as e:
        print(f"Error loading image {image_path}: {e}. Skipping.")
        return None

    # Processor handles both image and text inputs
    inputs = processor(image, question, return_tensors="pt")

    with torch.no_grad():
        outputs = model(**inputs)

    # Get the index of the highest logit
    logits = outputs.logits
    idx = logits.argmax(-1).item()

    # Map the index to the predicted answer string
    answer = model.config.id2label[idx]
    return answer.lower()

# --- Evaluate Model ---
correct = 0
total = 0
print("\n=== Evaluating Pre-trained VQA Model ===\n")

for img_path, question, true_answer in dataset:
    total += 1

    # Try to display the image (will only work in environments like Jupyter/Colab)
    try:
        image = Image.open(img_path).convert("RGB")
        display(image)
    except:
        pass # Skip display if running in console or image not found

    pred = vqa_predict(img_path, question)

    if pred is None:
        total -= 1
        continue

    # Standardize ground truth for comparison
    true_answer_lower = true_answer.lower().strip()
    pred_lower = pred.lower().strip()

    print(f"Image: {os.path.basename(img_path)}")
    print(f"Question: {question}")
    print(f"Predicted: {pred}")
    print(f"Actual: {true_answer}")

    if pred_lower == true_answer_lower:
        correct += 1
        print("Result: CORRECT 👍")
    else:
        print("Result: INCORRECT 👎")
    print("-" * 40)

# --- Final Accuracy ---
if total > 0:
    accuracy = (correct / total) * 100
    print(f"\nModel Accuracy: {accuracy:.2f}% (on {total} samples)")
else:
    print("\nEvaluation skipped: No images were successfully loaded.")

"""**Result:** Sucessfully used a pre-trained VQA model to answer questions about images and evaluated its performance."""